// AUTO-GENERATED — DO NOT EDIT
// 경량 키워드 딕셔너리 (seed → client bundle 최소화)

export type MajorKeyword = { keyword: string; id: string; category: string };
export type JobKeyword = { keyword: string; id: string };

export const MAJOR_KEYWORDS: MajorKeyword[] = [
  { keyword: "컴퓨터공학과", id: "computer-science", category: "공학계열" },
  { keyword: "전기전자공학과", id: "electrical-engineering", category: "공학계열" },
  { keyword: "기계공학과", id: "mechanical-engineering", category: "공학계열" },
  { keyword: "화학공학과", id: "chemical-engineering", category: "공학계열" },
  { keyword: "건축학과", id: "civil-engineering", category: "공학계열" },
  { keyword: "산업공학과", id: "industrial-engineering", category: "공학계열" },
  { keyword: "의공학과", id: "biomedical-engineering", category: "공학계열" },
  { keyword: "의예과", id: "medicine", category: "의약계열" },
  { keyword: "간호학과", id: "nursing", category: "의약계열" },
  { keyword: "약학과", id: "pharmacy", category: "의약계열" },
  { keyword: "경영학과", id: "business", category: "사회계열" },
  { keyword: "경제학과", id: "economics", category: "사회계열" },
  { keyword: "회계학과", id: "accounting", category: "사회계열" },
  { keyword: "법학과", id: "law", category: "사회계열" },
  { keyword: "정치외교학과", id: "political-science", category: "사회계열" },
  { keyword: "심리학과", id: "psychology", category: "사회계열" },
  { keyword: "사회학과", id: "sociology", category: "사회계열" },
  { keyword: "교육학과", id: "education", category: "교육계열" },
  { keyword: "국어교육과", id: "korean-language-edu", category: "교육계열" },
  { keyword: "영어영문학과", id: "english-language-lit", category: "인문계열" },
  { keyword: "국어국문학과", id: "korean-language-lit", category: "인문계열" },
  { keyword: "사학과", id: "history", category: "인문계열" },
  { keyword: "철학과", id: "philosophy", category: "인문계열" },
  { keyword: "생명과학과", id: "biology", category: "자연계열" },
  { keyword: "화학과", id: "chemistry", category: "자연계열" },
  { keyword: "수학과", id: "mathematics", category: "자연계열" },
  { keyword: "물리학과", id: "physics", category: "자연계열" },
  { keyword: "디자인학과", id: "design", category: "예체능계열" },
  { keyword: "미디어커뮤니케이션학과", id: "media-communication", category: "사회계열" },
  { keyword: "체육교육과", id: "physical-education", category: "교육계열" },
  { keyword: "불어불문학과", id: "french-lit", category: "인문계열" },
  { keyword: "독어독문학과", id: "german-lit", category: "인문계열" },
  { keyword: "일어일문학과", id: "japanese-lit", category: "인문계열" },
  { keyword: "중어중문학과", id: "chinese-lit", category: "인문계열" },
  { keyword: "노어노문학과", id: "russian-lit", category: "인문계열" },
  { keyword: "서어서문학과", id: "spanish-lit", category: "인문계열" },
  { keyword: "아랍어과", id: "arabic-lit", category: "인문계열" },
  { keyword: "베트남어과", id: "vietnamese-lit", category: "인문계열" },
  { keyword: "인도학과", id: "indian-lit", category: "인문계열" },
  { keyword: "동양사학과", id: "east-asian-history", category: "인문계열" },
  { keyword: "서양사학과", id: "western-history", category: "인문계열" },
  { keyword: "고고학과", id: "archaeology", category: "인문계열" },
  { keyword: "문화재학과", id: "cultural-heritage", category: "인문계열" },
  { keyword: "종교학과", id: "religion-studies", category: "인문계열" },
  { keyword: "신학과", id: "theology", category: "인문계열" },
  { keyword: "문화인류학과", id: "anthropology", category: "인문계열" },
  { keyword: "행정학과", id: "public-administration", category: "사회계열" },
  { keyword: "무역학과", id: "trade", category: "사회계열" },
  { keyword: "국제통상학과", id: "international-business", category: "사회계열" },
  { keyword: "호텔경영학과", id: "hotel-management", category: "사회계열" },
  { keyword: "관광경영학과", id: "tourism", category: "사회계열" },
  { keyword: "부동산학과", id: "real-estate", category: "사회계열" },
  { keyword: "광고홍보학과", id: "advertising", category: "사회계열" },
  { keyword: "사회복지학과", id: "social-welfare", category: "사회계열" },
  { keyword: "아동학과", id: "child-studies", category: "사회계열" },
  { keyword: "가족학과", id: "family-studies", category: "사회계열" },
  { keyword: "청소년학과", id: "youth-studies", category: "사회계열" },
  { keyword: "정책학과", id: "policy-studies", category: "사회계열" },
  { keyword: "신문방송학과", id: "broadcasting", category: "사회계열" },
  { keyword: "경찰행정학과", id: "police-admin", category: "사회계열" },
  { keyword: "군사학과", id: "military-studies", category: "사회계열" },
  { keyword: "보건행정학과", id: "health-admin", category: "사회계열" },
  { keyword: "도시행정학과", id: "urban-planning-social", category: "사회계열" },
  { keyword: "지리학과", id: "human-geography", category: "사회계열" },
  { keyword: "글로벌학과", id: "global-studies", category: "사회계열" },
  { keyword: "북한학과", id: "north-korea-studies", category: "사회계열" },
  { keyword: "소비자학과", id: "consumer-studies", category: "사회계열" },
  { keyword: "수학교육과", id: "math-edu", category: "교육계열" },
  { keyword: "영어교육과", id: "english-edu", category: "교육계열" },
  { keyword: "사회교육과", id: "social-edu", category: "교육계열" },
  { keyword: "과학교육과", id: "science-edu", category: "교육계열" },
  { keyword: "유아교육과", id: "early-childhood-edu", category: "교육계열" },
  { keyword: "초등교육과", id: "elementary-edu", category: "교육계열" },
  { keyword: "특수교육과", id: "special-edu", category: "교육계열" },
  { keyword: "윤리교육과", id: "ethics-edu", category: "교육계열" },
  { keyword: "미술교육과", id: "art-edu", category: "교육계열" },
  { keyword: "음악교육과", id: "music-edu", category: "교육계열" },
  { keyword: "기술교육과", id: "technology-edu", category: "교육계열" },
  { keyword: "가정교육과", id: "home-edu", category: "교육계열" },
  { keyword: "역사교육과", id: "history-edu", category: "교육계열" },
  { keyword: "정보통신공학과", id: "information-communication", category: "공학계열" },
  { keyword: "소프트웨어공학과", id: "software", category: "공학계열" },
  { keyword: "인공지능학과", id: "ai-engineering", category: "공학계열" },
  { keyword: "데이터사이언스학과", id: "data-science", category: "공학계열" },
  { keyword: "사이버보안학과", id: "cybersecurity", category: "공학계열" },
  { keyword: "게임공학과", id: "game-engineering", category: "공학계열" },
  { keyword: "항공우주공학과", id: "aerospace", category: "공학계열" },
  { keyword: "조선해양공학과", id: "naval-architecture", category: "공학계열" },
  { keyword: "자동차공학과", id: "automotive", category: "공학계열" },
  { keyword: "로봇공학과", id: "robotics", category: "공학계열" },
  { keyword: "메카트로닉스공학과", id: "mechatronics", category: "공학계열" },
  { keyword: "신소재공학과", id: "new-materials", category: "공학계열" },
  { keyword: "금속재료공학과", id: "metallurgy", category: "공학계열" },
  { keyword: "섬유공학과", id: "textile", category: "공학계열" },
  { keyword: "식품공학과", id: "food-engineering", category: "공학계열" },
  { keyword: "환경공학과", id: "environmental", category: "공학계열" },
  { keyword: "토목공학과", id: "civil-construction", category: "공학계열" },
  { keyword: "도시공학과", id: "urban-planning-eng", category: "공학계열" },
  { keyword: "교통공학과", id: "transportation", category: "공학계열" },
  { keyword: "시스템공학과", id: "systems", category: "공학계열" },
  { keyword: "원자력공학과", id: "nuclear", category: "공학계열" },
  { keyword: "에너지공학과", id: "energy", category: "공학계열" },
  { keyword: "나노공학과", id: "nano", category: "공학계열" },
  { keyword: "생명공학과", id: "bio-engineering", category: "공학계열" },
  { keyword: "산업디자인공학과", id: "industrial-design-eng", category: "공학계열" },
  { keyword: "자원공학과", id: "mining", category: "공학계열" },
  { keyword: "농업생명공학과", id: "agricultural-engineering", category: "공학계열" },
  { keyword: "해양공학과", id: "ocean-engineering", category: "공학계열" },
  { keyword: "지구과학과", id: "earth-science", category: "자연계열" },
  { keyword: "천문우주학과", id: "astronomy", category: "자연계열" },
  { keyword: "통계학과", id: "statistics", category: "자연계열" },
  { keyword: "대기과학과", id: "atmospheric", category: "자연계열" },
  { keyword: "해양학과", id: "oceanography", category: "자연계열" },
  { keyword: "지질학과", id: "geology", category: "자연계열" },
  { keyword: "농학과", id: "agriculture", category: "자연계열" },
  { keyword: "산림학과", id: "forestry", category: "자연계열" },
  { keyword: "원예학과", id: "horticulture", category: "자연계열" },
  { keyword: "동물자원학과", id: "animal-science", category: "자연계열" },
  { keyword: "수산생명의학과", id: "fisheries", category: "자연계열" },
  { keyword: "치의예과", id: "dentistry", category: "의약계열" },
  { keyword: "한의예과", id: "korean-medicine", category: "의약계열" },
  { keyword: "수의예과", id: "veterinary", category: "의약계열" },
  { keyword: "임상병리학과", id: "clinical-pathology", category: "의약계열" },
  { keyword: "방사선학과", id: "radiology", category: "의약계열" },
  { keyword: "작업치료학과", id: "occupational-therapy", category: "의약계열" },
  { keyword: "물리치료학과", id: "physical-therapy", category: "의약계열" },
  { keyword: "응급구조학과", id: "emergency-medical", category: "의약계열" },
  { keyword: "보건학과", id: "public-health", category: "의약계열" },
  { keyword: "시각디자인학과", id: "visual-design", category: "예체능계열" },
  { keyword: "산업디자인학과", id: "industrial-design", category: "예체능계열" },
  { keyword: "패션디자인학과", id: "fashion-design", category: "예체능계열" },
  { keyword: "실내건축디자인학과", id: "interior-design", category: "예체능계열" },
  { keyword: "동양화과", id: "painting-eastern", category: "예체능계열" },
  { keyword: "서양화과", id: "painting-western", category: "예체능계열" },
  { keyword: "조소과", id: "sculpture", category: "예체능계열" },
  { keyword: "도예과", id: "ceramic-art", category: "예체능계열" },
  { keyword: "사진학과", id: "photography", category: "예체능계열" },
  { keyword: "영화영상학과", id: "film-tv", category: "예체능계열" },
  { keyword: "만화애니메이션학과", id: "animation", category: "예체능계열" },
  { keyword: "게임그래픽디자인학과", id: "game-graphics", category: "예체능계열" },
  { keyword: "음악학과", id: "music-theory", category: "예체능계열" },
  { keyword: "작곡과", id: "composition", category: "예체능계열" },
  { keyword: "성악과", id: "vocal", category: "예체능계열" },
  { keyword: "피아노학과", id: "piano", category: "예체능계열" },
  { keyword: "관현악과", id: "orchestra", category: "예체능계열" },
  { keyword: "한국음악과", id: "korean-music", category: "예체능계열" },
  { keyword: "실용음악과", id: "applied-music", category: "예체능계열" },
  { keyword: "무용학과", id: "dance", category: "예체능계열" },
  { keyword: "연극영화학과", id: "theater-film", category: "예체능계열" },
  { keyword: "스포츠과학과", id: "sports-science", category: "예체능계열" },
  { keyword: "사회체육학과", id: "social-sports", category: "예체능계열" },
  { keyword: "태권도학과", id: "taekwondo", category: "예체능계열" }
];

export const MAJOR_CONCEPT_KEYWORDS: string[] = [
  "프로그래밍",
  "알고리즘",
  "AI",
  "소프트웨어",
  "데이터",
  "반도체",
  "회로",
  "통신",
  "제어",
  "임베디드",
  "역학",
  "CAD",
  "로봇",
  "자동차",
  "에너지",
  "반응공학",
  "공정",
  "신소재",
  "바이오",
  "설계",
  "공간",
  "도시",
  "디자인",
  "구조",
  "최적화",
  "물류",
  "품질",
  "경영과학",
  "의료기기",
  "헬스케어",
  "영상",
  "재활",
  "의사",
  "임상",
  "기초의학",
  "환자",
  "병원",
  "간호사",
  "공중보건",
  "돌봄",
  "약사",
  "신약",
  "제약",
  "화학",
  "마케팅",
  "재무",
  "전략",
  "조직",
  "창업",
  "거시경제",
  "금융",
  "통계",
  "정책",
  "분석",
  "회계사",
  "세무",
  "감사",
  "CPA",
  "법",
  "변호사",
  "로스쿨",
  "정의",
  "논리",
  "정치",
  "외교",
  "국제관계",
  "공직",
  "상담",
  "인지",
  "행동",
  "사회구조",
  "조사",
  "문화",
  "교육",
  "학습",
  "평생교육",
  "심리",
  "국어",
  "교사",
  "문학",
  "문법",
  "영어",
  "통번역",
  "영미문화",
  "언어학",
  "국어학",
  "출판",
  "콘텐츠",
  "글쓰기",
  "역사",
  "사료",
  "문명",
  "고고학",
  "박물관",
  "철학",
  "윤리",
  "사상",
  "비판적사고",
  "분자생물학",
  "유전",
  "생태",
  "의학",
  "유기화학",
  "분석화학",
  "실험",
  "수학",
  "보험",
  "양자역학",
  "전자기학",
  "이론물리",
  "연구",
  "UX",
  "그래픽",
  "브랜드",
  "산업디자인",
  "포트폴리오",
  "미디어",
  "저널리즘",
  "광고",
  "PR",
  "체육",
  "스포츠",
  "운동과학",
  "코칭",
  "프랑스어",
  "유럽",
  "독일어",
  "일본어",
  "중국어",
  "동양사상",
  "러시아어",
  "유라시아",
  "스페인어",
  "라틴아메리카",
  "아랍어",
  "중동",
  "이슬람",
  "베트남어",
  "동남아",
  "무역",
  "힌디어",
  "인도",
  "종교",
  "동양사",
  "중국사",
  "서양사",
  "유적",
  "발굴",
  "문화재",
  "복원",
  "보존",
  "비교",
  "신학",
  "성서",
  "기독교",
  "인류학",
  "민족지",
  "행정",
  "통상",
  "국제경영",
  "다국적",
  "호텔",
  "외식",
  "서비스",
  "관광",
  "여행",
  "문화관광",
  "부동산",
  "감정평가",
  "도시정책",
  "디지털 마케팅",
  "사회복지",
  "아동",
  "발달",
  "보육",
  "가족",
  "결혼",
  "청소년",
  "지도사",
  "평가",
  "방송",
  "PD",
  "경찰",
  "범죄학",
  "형사정책",
  "군사",
  "안보",
  "국방",
  "보건",
  "의료 경영",
  "지방자치",
  "지역개발",
  "지리",
  "GIS",
  "지역연구",
  "외국어",
  "북한",
  "통일",
  "소비자",
  "임용",
  "사회",
  "과학",
  "유아",
  "유치원",
  "초등",
  "교대",
  "특수교육",
  "장애",
  "통합교육",
  "도덕",
  "미술",
  "실기",
  "음악",
  "기술",
  "공작",
  "가정",
  "식품",
  "네트워크",
  "신호처리",
  "DevOps",
  "클라우드",
  "딥러닝",
  "NLP",
  "빅데이터",
  "보안",
  "암호",
  "포렌식",
  "게임",
  "그래픽스",
  "엔진",
  "항공",
  "우주",
  "추진",
  "조선",
  "해양",
  "선박",
  "전기차",
  "자율주행",
  "기계전자",
  "스마트팩토리",
  "배터리",
  "금속",
  "철강",
  "합금",
  "섬유",
  "고분자",
  "텍스타일",
  "발효",
  "가공",
  "환경",
  "수질",
  "탄소중립",
  "토목",
  "건설",
  "인프라",
  "도시계획",
  "교통",
  "ITS",
  "시스템",
  "신뢰성",
  "통합",
  "원자력",
  "방사선",
  "핵연료",
  "신재생",
  "수소",
  "나노",
  "소재",
  "유전공학",
  "세포",
  "인간공학",
  "자원",
  "광물",
  "시추",
  "스마트팜",
  "농업",
  "생명공학",
  "심해",
  "지구",
  "기후",
  "지질",
  "천문",
  "관측",
  "확률",
  "기상",
  "대기",
  "해류",
  "암석",
  "지층",
  "작물",
  "토양",
  "산림",
  "임업",
  "원예",
  "채소",
  "조경",
  "축산",
  "영양",
  "동물",
  "수산",
  "양식",
  "어병학",
  "치과",
  "구강",
  "한의학",
  "본초",
  "침구",
  "수의사",
  "검사",
  "병리",
  "혈액",
  "영상진단",
  "MRI",
  "작업치료",
  "노인",
  "물리치료",
  "운동치료",
  "응급",
  "심폐소생",
  "시각디자인",
  "제품",
  "운송",
  "가전",
  "패션",
  "의상",
  "MD",
  "인테리어",
  "조명",
  "동양화",
  "수묵",
  "전통",
  "회화",
  "유화",
  "현대미술",
  "조각",
  "설치",
  "공공미술",
  "도자기",
  "세라믹",
  "공예",
  "사진",
  "이미지",
  "다큐",
  "영화",
  "연출",
  "만화",
  "애니메이션",
  "웹툰",
  "캐릭터",
  "3D",
  "음악이론",
  "음악사",
  "비평",
  "작곡",
  "편곡",
  "이론",
  "성악",
  "오페라",
  "발성",
  "피아노",
  "연주",
  "레퍼토리",
  "관현악",
  "오케스트라",
  "악기",
  "국악",
  "전통음악",
  "가야금",
  "실용음악",
  "재즈",
  "프로듀싱",
  "무용",
  "안무",
  "발레",
  "연극",
  "연기",
  "생활체육",
  "레저",
  "건강",
  "태권도",
  "무도",
  "국제보급"
];

export const JOB_KEYWORDS: JobKeyword[] = [
  { keyword: "일기예보관", id: "5" },
  { keyword: "기상연구원", id: "6" },
  { keyword: "물리학연구원", id: "8" },
  { keyword: "방사선사", id: "10" },
  { keyword: "생물학연구원", id: "13" },
  { keyword: "수의사", id: "15" },
  { keyword: "수학연구원", id: "17" },
  { keyword: "의료장비기사", id: "19" },
  { keyword: "심리학연구원", id: "20" },
  { keyword: "안경사", id: "21" },
  { keyword: "약사 및 한약사", id: "23" },
  { keyword: "유전공학연구원", id: "24" },
  { keyword: "전문의사", id: "25" },
  { keyword: "지리학연구원", id: "29" },
  { keyword: "지질학연구원", id: "30" },
  { keyword: "천문학연구원", id: "31" },
  { keyword: "측량사", id: "32" },
  { keyword: "치과기공사", id: "33" },
  { keyword: "치과의사", id: "34" },
  { keyword: "통계학연구원", id: "36" },
  { keyword: "한의사", id: "37" },
  { keyword: "해부학연구원", id: "38" },
  { keyword: "해양학연구원", id: "39" },
  { keyword: "화학연구원", id: "40" },
  { keyword: "가전제품 설치 및 수리원", id: "41" },
  { keyword: "건설공사품질관리원", id: "42" },
  { keyword: "건축공학기술자", id: "46" },
  { keyword: "타이어 및 고무제품 생산직", id: "47" },
  { keyword: "공작기계조작원", id: "48" },
  { keyword: "광원 및 채석원", id: "49" },
  { keyword: "제화원", id: "50" },
  { keyword: "금속가공장치조작원", id: "52" },
  { keyword: "금속공학기술자", id: "53" },
  { keyword: "금형원", id: "54" },
  { keyword: "기계공학 기술자ㆍ연구원", id: "56" },
  { keyword: "섬유공학기술자", id: "57" },
  { keyword: "냉동기사", id: "58" },
  { keyword: "녹음기사", id: "59" },
  { keyword: "대기환경기술자", id: "61" },
  { keyword: "도배원", id: "63" },
  { keyword: "도자기제조원", id: "64" },
  { keyword: "건물도장원", id: "65" },
  { keyword: "로봇연구원", id: "66" },
  { keyword: "목공", id: "68" },
  { keyword: "목재가공관련조작원", id: "69" },
  { keyword: "미장원", id: "70" },
  { keyword: "방수원", id: "72" },
  { keyword: "섬유제조원", id: "73" },
  { keyword: "배관원", id: "74" },
  { keyword: "조적공", id: "75" },
  { keyword: "보석감정사", id: "76" },
  { keyword: "건설기계운전원", id: "77" },
  { keyword: "비파괴검사원", id: "81" },
  { keyword: "산업공학기술자", id: "83" },
  { keyword: "산업안전관리원", id: "84" },
  { keyword: "상ㆍ하수도 처리장치 조작원", id: "85" },
  { keyword: "생물공학연구원", id: "86" },
  { keyword: "석공", id: "87" },
  { keyword: "석유화학기술자", id: "88" },
  { keyword: "조선공학기술자", id: "90" },
  { keyword: "선박정비원", id: "92" },
  { keyword: "시멘트제조원", id: "97" },
  { keyword: "신경회로망연구원", id: "98" },
  { keyword: "압연원", id: "100" },
  { keyword: "영사기사", id: "101" },
  { keyword: "용접원", id: "102" },
  { keyword: "원자력연구원", id: "104" },
  { keyword: "유리제품제조원", id: "106" },
  { keyword: "인공위성개발원", id: "107" },
  { keyword: "인쇄기조작원", id: "108" },
  { keyword: "자동차정비원", id: "109" },
  { keyword: "자동차조립원", id: "110" },
  { keyword: "재료공학기술자", id: "112" },
  { keyword: "전공", id: "113" },
  { keyword: "전기공학기술자", id: "114" },
  { keyword: "전자공학기술자", id: "119" },
  { keyword: "전자장비설치 및 수리원", id: "120" },
  { keyword: "전화설치 및 수리원", id: "121" },
  { keyword: "정밀기기제품제조원", id: "122" },
  { keyword: "캐드원", id: "125" },
  { keyword: "단순노무자", id: "126" },
  { keyword: "주조원", id: "127" },
  { keyword: "직조원", id: "129" },
  { keyword: "철골공", id: "131" },
  { keyword: "철도 및 지하철기관사", id: "132" },
  { keyword: "철도차량정비원", id: "133" },
  { keyword: "토목공학기술자", id: "137" },
  { keyword: "통신공학 기술자 및 연구원", id: "138" },
  { keyword: "통신케이블설치 및 수리원", id: "139" },
  { keyword: "통신장비기사", id: "140" },
  { keyword: "트럭운전기사", id: "142" },
  { keyword: "판금원", id: "143" },
  { keyword: "펄프 및 종이 생산직", id: "144" },
  { keyword: "재활용 처리 및 소각로 조작원", id: "145" },
  { keyword: "플라스틱제품제조원", id: "147" },
  { keyword: "항공교통관제사", id: "148" },
  { keyword: "항공기정비원", id: "149" },
  { keyword: "비행기조종사", id: "150" },
  { keyword: "항공우주공학기술자", id: "151" },
  { keyword: "화학제품제조원", id: "153" },
  { keyword: "바닥재시공원", id: "155" },
  { keyword: "반도체공학기술자", id: "157" },
  { keyword: "가구제조,수리원", id: "159" },
  { keyword: "식품공학기술자", id: "162" },
  { keyword: "도축원 및 육류가공원", id: "163" },
  { keyword: "양장사 및 양복사", id: "164" },
  { keyword: "설문조사원", id: "165" },
  { keyword: "세탁원", id: "166" },
  { keyword: "소믈리에", id: "167" },
  { keyword: "영양사", id: "169" },
  { keyword: "전통식품제조원", id: "171" },
  { keyword: "제과사 및 제빵사", id: "172" },
  { keyword: "조리사 및 주방장", id: "173" },
  { keyword: "가축사육자", id: "174" },
  { keyword: "한복사", id: "175" },
  { keyword: "선장 및 항해사", id: "176" },
  { keyword: "푸드스타일리스트", id: "177" },
  { keyword: "쇼핑호스트", id: "178" },
  { keyword: "체형관리사", id: "179" },
  { keyword: "바리스타", id: "180" },
  { keyword: "농업기술자", id: "182" },
  { keyword: "곡식작물재배자", id: "183" },
  { keyword: "동물조련사", id: "186" },
  { keyword: "양식원", id: "187" },
  { keyword: "연근해 어부 및 해녀", id: "189" },
  { keyword: "유제품제조원", id: "190" },
  { keyword: "조경원", id: "192" },
  { keyword: "조경기술자", id: "193" },
  { keyword: "해양수산기술자", id: "195" },
  { keyword: "감정평가사", id: "198" },
  { keyword: "검사", id: "199" },
  { keyword: "상품중개인", id: "201" },
  { keyword: "경영컨설턴트", id: "202" },
  { keyword: "경제학연구원", id: "203" },
  { keyword: "노무사", id: "205" },
  { keyword: "회계사", id: "206" },
  { keyword: "관세사", id: "207" },
  { keyword: "국제무역사무원", id: "208" },
  { keyword: "국제회의전문가", id: "209" },
  { keyword: "농수산물중개인", id: "211" },
  { keyword: "도시 및 교통설계전문가", id: "212" },
  { keyword: "바이어(구매인)", id: "214" },
  { keyword: "물류관리사", id: "215" },
  { keyword: "보험계리인", id: "217" },
  { keyword: "부동산중개인", id: "219" },
  { keyword: "생활설계사", id: "222" },
  { keyword: "선물중개인", id: "223" },
  { keyword: "세무사", id: "224" },
  { keyword: "손해사정사", id: "226" },
  { keyword: "시장 및 여론조사전문가", id: "230" },
  { keyword: "신용조사원", id: "231" },
  { keyword: "광고 및 홍보전문가", id: "232" },
  { keyword: "외교관", id: "233" },
  { keyword: "외환딜러", id: "234" },
  { keyword: "자동차영업원", id: "236" },
  { keyword: "기업고위임원", id: "238" },
  { keyword: "증권분석가", id: "239" },
  { keyword: "증권중개인", id: "240" },
  { keyword: "텔레마케터", id: "242" },
  { keyword: "상점판매원", id: "243" },
  { keyword: "금융자산운용가(펀드매니저)", id: "244" },
  { keyword: "네이미스트", id: "247" },
  { keyword: "법률사무원", id: "252" },
  { keyword: "사무보조원", id: "253" },
  { keyword: "은행출납사무원", id: "255" },
  { keyword: "보건의료정보관리사", id: "256" },
  { keyword: "회계사무원", id: "258" },
  { keyword: "구성작가", id: "260" },
  { keyword: "극작가", id: "261" },
  { keyword: "기자", id: "262" },
  { keyword: "통역가", id: "264" },
  { keyword: "리포터", id: "265" },
  { keyword: "드라마작가", id: "266" },
  { keyword: "번역가", id: "267" },
  { keyword: "사서", id: "268" },
  { keyword: "정치학연구원", id: "269" },
  { keyword: "성우", id: "270" },
  { keyword: "아나운서", id: "271" },
  { keyword: "언어학연구원", id: "272" },
  { keyword: "역사학연구원", id: "273" },
  { keyword: "카피라이터", id: "278" },
  { keyword: "가수", id: "280" },
  { keyword: "개그맨", id: "281" },
  { keyword: "광고기획자", id: "283" },
  { keyword: "간판제작원", id: "284" },
  { keyword: "광고디자이너", id: "285" },
  { keyword: "국악인", id: "286" },
  { keyword: "네일아티스트", id: "288" },
  { keyword: "만화가", id: "291" },
  { keyword: "메이크업아티스트", id: "293" },
  { keyword: "모델", id: "294" },
  { keyword: "패턴사", id: "295" },
  { keyword: "무대감독", id: "296" },
  { keyword: "무용가", id: "298" },
  { keyword: "문화재보존원", id: "299" },
  { keyword: "방송연출가", id: "301" },
  { keyword: "연기자", id: "303" },
  { keyword: "백댄서(백업댄서)", id: "304" },
  { keyword: "보석디자이너", id: "305" },
  { keyword: "분장사", id: "306" },
  { keyword: "비디오저널리스트(VJ)", id: "309" },
  { keyword: "사진작가", id: "310" },
  { keyword: "사진인화 및 현상관련조작원", id: "311" },
  { keyword: "성악가", id: "313" },
  { keyword: "스턴트맨", id: "314" },
  { keyword: "플로리스트", id: "316" },
  { keyword: "연주가", id: "317" },
  { keyword: "악기제조원", id: "318" },
  { keyword: "반려동물미용사", id: "319" },
  { keyword: "연극연출가", id: "320" },
  { keyword: "연예인매니저", id: "321" },
  { keyword: "영화감독", id: "322" },
  { keyword: "영화기획자", id: "323" },
  { keyword: "이미지컨설턴트", id: "325" },
  { keyword: "인테리어디자이너", id: "326" },
  { keyword: "일러스트레이터", id: "327" },
  { keyword: "작곡가", id: "328" },
  { keyword: "제품디자이너", id: "332" },
  { keyword: "조각가", id: "333" },
  { keyword: "조향사", id: "334" },
  { keyword: "지휘자", id: "335" },
  { keyword: "운동선수", id: "336" },
  { keyword: "촬영기사", id: "337" },
  { keyword: "출판물기획전문가", id: "338" },
  { keyword: "캐릭터디자이너", id: "339" },
  { keyword: "컬러리스트", id: "340" },
  { keyword: "패션디자이너", id: "344" },
  { keyword: "패션코디네이터", id: "345" },
  { keyword: "편집기사", id: "346" },
  { keyword: "악기수리원 및 조율사", id: "347" },
  { keyword: "학예사(큐레이터)", id: "348" },
  { keyword: "화가", id: "349" },
  { keyword: "가사도우미", id: "352" },
  { keyword: "간병인", id: "353" },
  { keyword: "간호사", id: "354" },
  { keyword: "간호조무사", id: "355" },
  { keyword: "청소원", id: "356" },
  { keyword: "경비원", id: "358" },
  { keyword: "경찰관", id: "359" },
  { keyword: "경호원", id: "360" },
  { keyword: "일반공무원", id: "362" },
  { keyword: "교도관", id: "363" },
  { keyword: "이공학계열교수", id: "364" },
  { keyword: "독서지도사", id: "365" },
  { keyword: "레크리에이션지도자", id: "366" },
  { keyword: "물리치료사", id: "369" },
  { keyword: "바텐더", id: "370" },
  { keyword: "택배원", id: "371" },
  { keyword: "버스운전기사", id: "372" },
  { keyword: "법무사", id: "373" },
  { keyword: "변리사", id: "374" },
  { keyword: "변호사", id: "375" },
  { keyword: "보육교사", id: "376" },
  { keyword: "전문비서", id: "378" },
  { keyword: "사회복지사", id: "379" },
  { keyword: "상담전문가", id: "380" },
  { keyword: "우편물집배원", id: "383" },
  { keyword: "성직자", id: "384" },
  { keyword: "소방관", id: "385" },
  { keyword: "언어치료사", id: "386" },
  { keyword: "여행안내원", id: "388" },
  { keyword: "신호원 및 수송원", id: "390" },
  { keyword: "운동경기심판", id: "391" },
  { keyword: "스포츠트레이너", id: "392" },
  { keyword: "유치원교사", id: "395" },
  { keyword: "음악치료사", id: "396" },
  { keyword: "응급구조사", id: "397" },
  { keyword: "임상심리사", id: "398" },
  { keyword: "운동감독", id: "400" },
  { keyword: "작업치료사", id: "401" },
  { keyword: "장례지도사", id: "403" },
  { keyword: "전화교환원", id: "404" },
  { keyword: "주택관리사", id: "405" },
  { keyword: "인문계중등학교교사", id: "406" },
  { keyword: "직업군인", id: "407" },
  { keyword: "직업상담 및 취업알선원", id: "408" },
  { keyword: "직업능력개발훈련교사", id: "409" },
  { keyword: "초등학교교사", id: "410" },
  { keyword: "치과위생사", id: "411" },
  { keyword: "캐디", id: "412" },
  { keyword: "특수교사", id: "413" },
  { keyword: "판사", id: "414" },
  { keyword: "프로바둑기사", id: "415" },
  { keyword: "피부관리사", id: "416" },
  { keyword: "학원강사", id: "417" },
  { keyword: "비행기승무원", id: "418" },
  { keyword: "홍보도우미", id: "419" },
  { keyword: "스포츠강사", id: "421" },
  { keyword: "택시운전기사", id: "426" },
  { keyword: "웨딩플래너", id: "427" },
  { keyword: "호스피스전문간호사", id: "428" },
  { keyword: "통신엔지니어", id: "429" },
  { keyword: "네트워크엔지니어", id: "430" },
  { keyword: "데이터베이스관리자", id: "431" },
  { keyword: "정보보호전문가", id: "435" },
  { keyword: "시스템엔지니어", id: "440" },
  { keyword: "애니메이터", id: "441" },
  { keyword: "웹디자이너", id: "443" },
  { keyword: "웹마스터", id: "444" },
  { keyword: "IT컨설턴트", id: "450" },
  { keyword: "정보중개인", id: "452" },
  { keyword: "컴퓨터게임시나리오작가", id: "457" },
  { keyword: "컴퓨터그래픽디자이너", id: "458" },
  { keyword: "속기사", id: "459" },
  { keyword: "사이버교육운영자", id: "462" },
  { keyword: "통신망설계운영기술자", id: "465" },
  { keyword: "컴퓨터설치·수리원", id: "466" },
  { keyword: "의료정보시스템개발자", id: "467" },
  { keyword: "전자상거래전문가", id: "470" },
  { keyword: "아이티(IT)기술영업원", id: "474" },
  { keyword: "아이티(IT)교육강사", id: "475" },
  { keyword: "무선주파수(RF)엔지니어", id: "476" },
  { keyword: "교장", id: "481" },
  { keyword: "소음진동기술자", id: "539" },
  { keyword: "크레인 및 호이스트운전원", id: "592" },
  { keyword: "여행상품개발원", id: "626" },
  { keyword: "귀금속 및 보석세공원", id: "740" },
  { keyword: "호텔지배인", id: "795" },
  { keyword: "시스템소프트웨어개발자", id: "834" },
  { keyword: "조명기사", id: "911" },
  { keyword: "영화시나리오작가", id: "914" },
  { keyword: "음향기사", id: "915" },
  { keyword: "특수효과기술자", id: "916" },
  { keyword: "음반기획자", id: "917" },
  { keyword: "애니메이션기획자", id: "920" },
  { keyword: "애니메이션작가", id: "922" },
  { keyword: "게임기획자", id: "923" },
  { keyword: "출판편집자", id: "926" },
  { keyword: "북디자이너", id: "927" },
  { keyword: "영업원", id: "928" },
  { keyword: "공예원", id: "929" },
  { keyword: "사회학연구원", id: "933" },
  { keyword: "사회단체활동가", id: "934" },
  { keyword: "시각디자이너", id: "937" },
  { keyword: "정보시스템운영자", id: "938" },
  { keyword: "임상병리사", id: "941" },
  { keyword: "카지노딜러", id: "946" },
  { keyword: "컴퓨터하드웨어 기술자 및 연구원", id: "948" },
  { keyword: "투자분석가(애널리스트)", id: "950" },
  { keyword: "행사기획자", id: "951" },
  { keyword: "화학공학기술자", id: "952" },
  { keyword: "화훼재배기술자", id: "954" },
  { keyword: "평론가", id: "957" },
  { keyword: "원예기술자", id: "963" },
  { keyword: "안무가", id: "966" },
  { keyword: "시인", id: "968" },
  { keyword: "소설가", id: "973" },
  { keyword: "사진사", id: "975" },
  { keyword: "사진기자", id: "976" },
  { keyword: "보일러공", id: "978" },
  { keyword: "공업기계설치 및 정비원", id: "985" },
  { keyword: "인문사회계열교수", id: "988" },
  { keyword: "환경컨설턴트", id: "994" },
  { keyword: "에너지공학기술자", id: "995" },
  { keyword: "토양환경기술자", id: "997" },
  { keyword: "환경설비기술자", id: "1004" },
  { keyword: "해양환경기사", id: "1006" },
  { keyword: "상수도기술자", id: "1007" },
  { keyword: "환경위생검사원", id: "1009" },
  { keyword: "방사성폐기물관리원", id: "1010" },
  { keyword: "국회의원", id: "1061" },
  { keyword: "마케팅전문가", id: "1068" },
  { keyword: "자동차공학기술자", id: "1076" },
  { keyword: "대형트럭 및 특수차운전원", id: "1078" },
  { keyword: "환경공학기술자 및 연구원", id: "1080" },
  { keyword: "해양공학기술자", id: "1081" },
  { keyword: "전자 부품 및 제품 생산직", id: "1087" },
  { keyword: "스포츠에이전트", id: "1088" },
  { keyword: "자연계중등학교교사", id: "1089" },
  { keyword: "콘크리트공", id: "1090" },
  { keyword: "GIS전문가", id: "1092" },
  { keyword: "가상현실전문가", id: "1093" },
  { keyword: "웹프로듀서", id: "1096" },
  { keyword: "프로게이머", id: "1097" },
  { keyword: "군무원", id: "1100" },
  { keyword: "신용관련추심원", id: "1101" },
  { keyword: "장학사", id: "1102" },
  { keyword: "교육학연구원", id: "1103" },
  { keyword: "철학연구원", id: "1104" },
  { keyword: "행정학연구원", id: "1105" },
  { keyword: "학습지방문교사", id: "1106" },
  { keyword: "안마사", id: "1107" },
  { keyword: "위생사", id: "1108" },
  { keyword: "서예가", id: "1109" },
  { keyword: "도선사", id: "1110" },
  { keyword: "지게차운전원", id: "1111" },
  { keyword: "선박갑판원", id: "1112" },
  { keyword: "방문판매원", id: "1113" },
  { keyword: "상품대여원", id: "1114" },
  { keyword: "주유원", id: "1115" },
  { keyword: "계산원 및 매표원", id: "1116" },
  { keyword: "청원경찰", id: "1117" },
  { keyword: "무인경비시스템종사원", id: "1118" },
  { keyword: "구두미화원 및 수선원", id: "1119" },
  { keyword: "주차관리원", id: "1120" },
  { keyword: "이용사", id: "1121" },
  { keyword: "미용사", id: "1122" },
  { keyword: "혼례종사원", id: "1124" },
  { keyword: "선박 및 열차객실승무원", id: "1125" },
  { keyword: "치어리더", id: "1126" },
  { keyword: "접객원", id: "1127" },
  { keyword: "주방보조원", id: "1128" },
  { keyword: "요리배달원", id: "1129" },
  { keyword: "건설견적원", id: "1130" },
  { keyword: "전통건축원", id: "1131" },
  { keyword: "단열원", id: "1132" },
  { keyword: "유리부착원", id: "1133" },
  { keyword: "메카트로닉스공학기술자", id: "1134" },
  { keyword: "공구제조원", id: "1135" },
  { keyword: "항공기·선박조립 및 검사원", id: "1136" },
  { keyword: "제관원", id: "1137" },
  { keyword: "새시원", id: "1138" },
  { keyword: "단조원", id: "1139" },
  { keyword: "도장원", id: "1140" },
  { keyword: "도금원", id: "1141" },
  { keyword: "의복수선원", id: "1142" },
  { keyword: "의복제품검사원", id: "1143" },
  { keyword: "발전장치조작원", id: "1144" },
  { keyword: "전기설비조작원", id: "1145" },
  { keyword: "전기 부품 및 제품 생산직", id: "1146" },
  { keyword: "통신설비설치 및 수리원", id: "1148" },
  { keyword: "음료제조관련조작원", id: "1149" },
  { keyword: "식품가공검사원", id: "1150" },
  { keyword: "종이제품생산직(기계조작)", id: "1151" },
  { keyword: "가구조립 및 검사원", id: "1152" },
  { keyword: "포장원", id: "1153" },
  { keyword: "채소 및 특용작물재배자", id: "1154" },
  { keyword: "과수작물재배자", id: "1155" },
  { keyword: "조림 영림 및 벌목원", id: "1156" },
  { keyword: "원양어부", id: "1157" },
  { keyword: "수질환경연구원", id: "1255" },
  { keyword: "커플매니저", id: "1256" },
  { keyword: "병원코디네이터", id: "1257" },
  { keyword: "마술사", id: "1259" },
  { keyword: "파티플래너", id: "1276" },
  { keyword: "건축사", id: "1277" },
  { keyword: "행정부고위공무원", id: "1278" },
  { keyword: "헤드헌터", id: "1279" },
  { keyword: "환경영향평가원", id: "1281" },
  { keyword: "대체에너지개발연구원", id: "1282" },
  { keyword: "음악강사", id: "1431" },
  { keyword: "베타테스터", id: "1432" },
  { keyword: "발명가", id: "1433" },
  { keyword: "신약개발연구원", id: "1436" },
  { keyword: "스포츠해설가", id: "1437" },
  { keyword: "카레이서", id: "1438" },
  { keyword: "캐스팅디렉터", id: "1439" },
  { keyword: "일반의사", id: "1440" },
  { keyword: "작가", id: "1441" },
  { keyword: "자연과학연구원", id: "1541" },
  { keyword: "3D 프린팅 전문가", id: "10001" },
  { keyword: "홀로그램 전문가", id: "10002" },
  { keyword: "UX 디자인 컨설턴트", id: "10003" },
  { keyword: "도시 재생 전문가", id: "10004" },
  { keyword: "스마트 도시 전문가", id: "10005" },
  { keyword: "곤충 음식 개발자·조리사", id: "10006" },
  { keyword: "정밀 농업기술자", id: "10007" },
  { keyword: "스마트 팜 구축가", id: "10008" },
  { keyword: "스마트 의류 개발자", id: "10009" },
  { keyword: "원격진료 코디네이터", id: "10010" },
  { keyword: "노년 플래너", id: "10011" },
  { keyword: "헬스 케어 컨설턴트", id: "10012" },
  { keyword: "노인 전문 간호사", id: "10013" },
  { keyword: "의료 기기 개발 전문가", id: "10014" },
  { keyword: "스포츠 심리 상담원", id: "10015" },
  { keyword: "여행 기획자", id: "10016" },
  { keyword: "해양 레저 전문가", id: "10017" },
  { keyword: "반려동물 훈련·상담사", id: "10018" },
  { keyword: "디지털 큐레이터", id: "10019" },
  { keyword: "게임 방송 프로듀서", id: "10020" },
  { keyword: "드론 콘텐츠 전문가", id: "10022" },
  { keyword: "문화 콘텐츠 전문가", id: "10023" },
  { keyword: "해양 에너지 기술자", id: "10024" },
  { keyword: "스마트 그리드 엔지니어", id: "10025" },
  { keyword: "기후변화 대응 전문가", id: "10026" },
  { keyword: "신재생에너지 전문가", id: "10027" },
  { keyword: "스마트 재난 관리 전문가", id: "10028" },
  { keyword: "블록체인 전문가", id: "10029" },
  { keyword: "디지털 포렌식 수사관", id: "10030" },
  { keyword: "클라우드 시스템 엔지니어", id: "10031" },
  { keyword: "빅 데이터 전문가", id: "10032" },
  { keyword: "크라우드 펀딩 전문가", id: "10033" },
  { keyword: "사이버 평판 관리자", id: "10034" },
  { keyword: "사물 인터넷 전문가", id: "10035" },
  { keyword: "생체 인식 전문가", id: "10036" },
  { keyword: "생물 정보 분석가", id: "10037" },
  { keyword: "로봇 윤리학자", id: "10038" },
  { keyword: "드론 전문가", id: "10039" },
  { keyword: "손실방지전문가", id: "10040" },
  { keyword: "소비생활어드바이저", id: "10041" },
  { keyword: "문화여가사", id: "10042" },
  { keyword: "개인브랜드매니저", id: "10043" },
  { keyword: "개인관리컨설턴트", id: "10044" },
  { keyword: "재활용코디네이터", id: "10045" },
  { keyword: "동물보호보안관", id: "10046" },
  { keyword: "식품융합엔지니어", id: "10047" },
  { keyword: "수의테크니션", id: "10048" },
  { keyword: "무인항공기시스템개발자", id: "10049" },
  { keyword: "지리정보시스템기사", id: "10050" },
  { keyword: "데이터마이너", id: "10051" },
  { keyword: "웹접근성컨설턴트", id: "10052" },
  { keyword: "산업카운슬러", id: "10053" },
  { keyword: "괴롭힘방지조언사", id: "10054" },
  { keyword: "재능기부코디네이터", id: "10055" },
  { keyword: "장애인잡코치", id: "10056" },
  { keyword: "아동청소년시설보호사", id: "10057" },
  { keyword: "케어매니저", id: "10058" },
  { keyword: "평등관리사무원", id: "10059" },
  { keyword: "애견테라피스트", id: "10060" },
  { keyword: "유전상담사", id: "10061" },
  { keyword: "학습장애간호사", id: "10062" },
  { keyword: "사설탐정", id: "10063" },
  { keyword: "범죄과학수사관", id: "10064" },
  { keyword: "야외활동지도사", id: "10065" },
  { keyword: "스포츠기록분석연구원", id: "10066" },
  { keyword: "비디오게임디자이너", id: "10067" },
  { keyword: "게임감시관 및 조사관", id: "10068" },
  { keyword: "목소리코치", id: "10069" },
  { keyword: "무인항공촬영감독", id: "10070" },
  { keyword: "동물랭글러", id: "10071" },
  { keyword: "웹툰작가", id: "10072" },
  { keyword: "아쿠아리스트", id: "10073" },
  { keyword: "범죄심리분석관(프로파일러)", id: "10074" },
  { keyword: "다문화코디네이터", id: "10075" },
  { keyword: "모바일앱개발자", id: "10076" },
  { keyword: "SNS 마케터", id: "10077" },
  { keyword: "국제개발협력전문가", id: "10078" },
  { keyword: "창업컨설턴트", id: "10079" },
  { keyword: "공정무역전문가", id: "10080" },
  { keyword: "메타버스 크리에이터", id: "10101" },
  { keyword: "감성인식기술전문가", id: "10102" },
  { keyword: "개인형 이동수단 개발자", id: "10103" },
  { keyword: "유전자 재조합 식품 전문가", id: "10104" },
  { keyword: "태양광발전연구 및 개발자", id: "10105" },
  { keyword: "스마트팜 운영자", id: "10106" },
  { keyword: "디스플레이 개발자", id: "10107" },
  { keyword: "배터리 기술자", id: "10108" },
  { keyword: "나노공학 기술자", id: "10109" },
  { keyword: "양자 컴퓨팅 기술자", id: "10110" },
  { keyword: "핀테크 전문가", id: "10111" },
  { keyword: "스마트공장 기술자", id: "10112" },
  { keyword: "지능형 로봇개발자", id: "10113" },
  { keyword: "우주전파예보관", id: "10114" },
  { keyword: "디지털 헬스케어 기기 개발자", id: "10115" },
  { keyword: "신소재 개발 연구원", id: "10116" },
  { keyword: "인공지능 엔지니어", id: "10117" },
  { keyword: "데이터 라벨러", id: "10118" }
];

export const FIELD_KEYWORDS: string[] = [
  "AI",
  "인공지능",
  "빅데이터",
  "머신러닝",
  "딥러닝",
  "클라우드",
  "반도체",
  "바이오",
  "헬스케어",
  "핀테크",
  "메타버스",
  "로봇",
  "스타트업",
  "창업",
  "의료",
  "법학",
  "회계",
  "마케팅",
  "디자인",
  "심리",
  "사회복지",
  "교육",
  "연구",
  "개발",
  "환경",
  "에너지",
  "건축",
  "도시",
  "역학",
  "통신",
  "전기",
  "화학",
  "생명",
  "의약",
  "게임",
  "애니메이션",
  "패션",
  "음악",
  "미술",
  "스포츠",
  "경영",
  "금융",
  "경제",
  "철학",
  "역사",
  "지리",
  "사회",
  "정치",
  "외교",
  "언어",
  "문학",
  "영화",
  "방송"
];
