// AUTO-GENERATED by scripts/gen-major-kw-map.mjs — DO NOT EDIT
// seed/majors.json의 keywords 필드를 역방향 색인한 맵
// keyword → [{id, name, category}] 형태로 어느 학과에 속하는지 알 수 있음

export type MajorRef = { id: string; name: string; category: string };

export const MAJOR_KW_MAP: Record<string, MajorRef[]> = {
  "프로그래밍": [
    {
      "id": "computer-science",
      "name": "컴퓨터공학과",
      "category": "공학계열"
    }
  ],
  "알고리즘": [
    {
      "id": "computer-science",
      "name": "컴퓨터공학과",
      "category": "공학계열"
    }
  ],
  "AI": [
    {
      "id": "computer-science",
      "name": "컴퓨터공학과",
      "category": "공학계열"
    },
    {
      "id": "ai-engineering",
      "name": "인공지능학과",
      "category": "공학계열"
    },
    {
      "id": "robotics",
      "name": "로봇공학과",
      "category": "공학계열"
    }
  ],
  "소프트웨어": [
    {
      "id": "computer-science",
      "name": "컴퓨터공학과",
      "category": "공학계열"
    },
    {
      "id": "software",
      "name": "소프트웨어공학과",
      "category": "공학계열"
    }
  ],
  "데이터": [
    {
      "id": "computer-science",
      "name": "컴퓨터공학과",
      "category": "공학계열"
    },
    {
      "id": "industrial-engineering",
      "name": "산업공학과",
      "category": "공학계열"
    },
    {
      "id": "mathematics",
      "name": "수학과",
      "category": "자연계열"
    },
    {
      "id": "data-science",
      "name": "데이터사이언스학과",
      "category": "공학계열"
    },
    {
      "id": "statistics",
      "name": "통계학과",
      "category": "자연계열"
    },
    {
      "id": "sports-science",
      "name": "스포츠과학과",
      "category": "예체능계열"
    }
  ],
  "반도체": [
    {
      "id": "electrical-engineering",
      "name": "전기전자공학과",
      "category": "공학계열"
    },
    {
      "id": "physics",
      "name": "물리학과",
      "category": "자연계열"
    },
    {
      "id": "new-materials",
      "name": "신소재공학과",
      "category": "공학계열"
    },
    {
      "id": "nano",
      "name": "나노공학과",
      "category": "공학계열"
    }
  ],
  "회로": [
    {
      "id": "electrical-engineering",
      "name": "전기전자공학과",
      "category": "공학계열"
    }
  ],
  "통신": [
    {
      "id": "electrical-engineering",
      "name": "전기전자공학과",
      "category": "공학계열"
    },
    {
      "id": "information-communication",
      "name": "정보통신공학과",
      "category": "공학계열"
    }
  ],
  "제어": [
    {
      "id": "electrical-engineering",
      "name": "전기전자공학과",
      "category": "공학계열"
    },
    {
      "id": "robotics",
      "name": "로봇공학과",
      "category": "공학계열"
    },
    {
      "id": "mechatronics",
      "name": "메카트로닉스공학과",
      "category": "공학계열"
    }
  ],
  "임베디드": [
    {
      "id": "electrical-engineering",
      "name": "전기전자공학과",
      "category": "공학계열"
    }
  ],
  "역학": [
    {
      "id": "mechanical-engineering",
      "name": "기계공학과",
      "category": "공학계열"
    },
    {
      "id": "public-health",
      "name": "보건학과",
      "category": "의약계열"
    }
  ],
  "CAD": [
    {
      "id": "mechanical-engineering",
      "name": "기계공학과",
      "category": "공학계열"
    }
  ],
  "로봇": [
    {
      "id": "mechanical-engineering",
      "name": "기계공학과",
      "category": "공학계열"
    },
    {
      "id": "robotics",
      "name": "로봇공학과",
      "category": "공학계열"
    }
  ],
  "자동차": [
    {
      "id": "mechanical-engineering",
      "name": "기계공학과",
      "category": "공학계열"
    },
    {
      "id": "automotive",
      "name": "자동차공학과",
      "category": "공학계열"
    }
  ],
  "에너지": [
    {
      "id": "mechanical-engineering",
      "name": "기계공학과",
      "category": "공학계열"
    },
    {
      "id": "chemical-engineering",
      "name": "화학공학과",
      "category": "공학계열"
    },
    {
      "id": "energy",
      "name": "에너지공학과",
      "category": "공학계열"
    }
  ],
  "반응공학": [
    {
      "id": "chemical-engineering",
      "name": "화학공학과",
      "category": "공학계열"
    }
  ],
  "공정": [
    {
      "id": "chemical-engineering",
      "name": "화학공학과",
      "category": "공학계열"
    }
  ],
  "신소재": [
    {
      "id": "chemical-engineering",
      "name": "화학공학과",
      "category": "공학계열"
    },
    {
      "id": "chemistry",
      "name": "화학과",
      "category": "자연계열"
    },
    {
      "id": "new-materials",
      "name": "신소재공학과",
      "category": "공학계열"
    }
  ],
  "바이오": [
    {
      "id": "chemical-engineering",
      "name": "화학공학과",
      "category": "공학계열"
    },
    {
      "id": "biomedical-engineering",
      "name": "의공학과",
      "category": "공학계열"
    },
    {
      "id": "biology",
      "name": "생명과학과",
      "category": "자연계열"
    },
    {
      "id": "bio-engineering",
      "name": "생명공학과",
      "category": "공학계열"
    }
  ],
  "설계": [
    {
      "id": "civil-engineering",
      "name": "건축학과",
      "category": "공학계열"
    }
  ],
  "공간": [
    {
      "id": "civil-engineering",
      "name": "건축학과",
      "category": "공학계열"
    },
    {
      "id": "human-geography",
      "name": "지리학과",
      "category": "사회계열"
    },
    {
      "id": "interior-design",
      "name": "실내건축디자인학과",
      "category": "예체능계열"
    }
  ],
  "도시": [
    {
      "id": "civil-engineering",
      "name": "건축학과",
      "category": "공학계열"
    },
    {
      "id": "urban-planning-social",
      "name": "도시행정학과",
      "category": "사회계열"
    }
  ],
  "디자인": [
    {
      "id": "civil-engineering",
      "name": "건축학과",
      "category": "공학계열"
    }
  ],
  "구조": [
    {
      "id": "civil-engineering",
      "name": "건축학과",
      "category": "공학계열"
    },
    {
      "id": "emergency-medical",
      "name": "응급구조학과",
      "category": "의약계열"
    }
  ],
  "최적화": [
    {
      "id": "industrial-engineering",
      "name": "산업공학과",
      "category": "공학계열"
    }
  ],
  "물류": [
    {
      "id": "industrial-engineering",
      "name": "산업공학과",
      "category": "공학계열"
    },
    {
      "id": "trade",
      "name": "무역학과",
      "category": "사회계열"
    },
    {
      "id": "transportation",
      "name": "교통공학과",
      "category": "공학계열"
    }
  ],
  "품질": [
    {
      "id": "industrial-engineering",
      "name": "산업공학과",
      "category": "공학계열"
    }
  ],
  "경영과학": [
    {
      "id": "industrial-engineering",
      "name": "산업공학과",
      "category": "공학계열"
    }
  ],
  "의료기기": [
    {
      "id": "biomedical-engineering",
      "name": "의공학과",
      "category": "공학계열"
    }
  ],
  "헬스케어": [
    {
      "id": "biomedical-engineering",
      "name": "의공학과",
      "category": "공학계열"
    }
  ],
  "영상": [
    {
      "id": "biomedical-engineering",
      "name": "의공학과",
      "category": "공학계열"
    },
    {
      "id": "film-tv",
      "name": "영화영상학과",
      "category": "예체능계열"
    }
  ],
  "재활": [
    {
      "id": "biomedical-engineering",
      "name": "의공학과",
      "category": "공학계열"
    },
    {
      "id": "occupational-therapy",
      "name": "작업치료학과",
      "category": "의약계열"
    },
    {
      "id": "physical-therapy",
      "name": "물리치료학과",
      "category": "의약계열"
    }
  ],
  "의사": [
    {
      "id": "medicine",
      "name": "의예과",
      "category": "의약계열"
    }
  ],
  "임상": [
    {
      "id": "medicine",
      "name": "의예과",
      "category": "의약계열"
    },
    {
      "id": "pharmacy",
      "name": "약학과",
      "category": "의약계열"
    },
    {
      "id": "psychology",
      "name": "심리학과",
      "category": "사회계열"
    },
    {
      "id": "dentistry",
      "name": "치의예과",
      "category": "의약계열"
    },
    {
      "id": "veterinary",
      "name": "수의예과",
      "category": "의약계열"
    }
  ],
  "기초의학": [
    {
      "id": "medicine",
      "name": "의예과",
      "category": "의약계열"
    }
  ],
  "환자": [
    {
      "id": "medicine",
      "name": "의예과",
      "category": "의약계열"
    },
    {
      "id": "nursing",
      "name": "간호학과",
      "category": "의약계열"
    }
  ],
  "병원": [
    {
      "id": "medicine",
      "name": "의예과",
      "category": "의약계열"
    },
    {
      "id": "nursing",
      "name": "간호학과",
      "category": "의약계열"
    }
  ],
  "간호사": [
    {
      "id": "nursing",
      "name": "간호학과",
      "category": "의약계열"
    }
  ],
  "공중보건": [
    {
      "id": "nursing",
      "name": "간호학과",
      "category": "의약계열"
    },
    {
      "id": "public-health",
      "name": "보건학과",
      "category": "의약계열"
    }
  ],
  "돌봄": [
    {
      "id": "nursing",
      "name": "간호학과",
      "category": "의약계열"
    }
  ],
  "약사": [
    {
      "id": "pharmacy",
      "name": "약학과",
      "category": "의약계열"
    }
  ],
  "신약": [
    {
      "id": "pharmacy",
      "name": "약학과",
      "category": "의약계열"
    }
  ],
  "제약": [
    {
      "id": "pharmacy",
      "name": "약학과",
      "category": "의약계열"
    },
    {
      "id": "chemistry",
      "name": "화학과",
      "category": "자연계열"
    }
  ],
  "화학": [
    {
      "id": "pharmacy",
      "name": "약학과",
      "category": "의약계열"
    }
  ],
  "마케팅": [
    {
      "id": "business",
      "name": "경영학과",
      "category": "사회계열"
    }
  ],
  "재무": [
    {
      "id": "business",
      "name": "경영학과",
      "category": "사회계열"
    },
    {
      "id": "accounting",
      "name": "회계학과",
      "category": "사회계열"
    }
  ],
  "전략": [
    {
      "id": "business",
      "name": "경영학과",
      "category": "사회계열"
    }
  ],
  "조직": [
    {
      "id": "business",
      "name": "경영학과",
      "category": "사회계열"
    }
  ],
  "창업": [
    {
      "id": "business",
      "name": "경영학과",
      "category": "사회계열"
    }
  ],
  "거시경제": [
    {
      "id": "economics",
      "name": "경제학과",
      "category": "사회계열"
    }
  ],
  "금융": [
    {
      "id": "economics",
      "name": "경제학과",
      "category": "사회계열"
    }
  ],
  "통계": [
    {
      "id": "economics",
      "name": "경제학과",
      "category": "사회계열"
    },
    {
      "id": "psychology",
      "name": "심리학과",
      "category": "사회계열"
    },
    {
      "id": "sociology",
      "name": "사회학과",
      "category": "사회계열"
    },
    {
      "id": "mathematics",
      "name": "수학과",
      "category": "자연계열"
    },
    {
      "id": "data-science",
      "name": "데이터사이언스학과",
      "category": "공학계열"
    },
    {
      "id": "statistics",
      "name": "통계학과",
      "category": "자연계열"
    }
  ],
  "정책": [
    {
      "id": "economics",
      "name": "경제학과",
      "category": "사회계열"
    },
    {
      "id": "political-science",
      "name": "정치외교학과",
      "category": "사회계열"
    },
    {
      "id": "sociology",
      "name": "사회학과",
      "category": "사회계열"
    },
    {
      "id": "education",
      "name": "교육학과",
      "category": "교육계열"
    },
    {
      "id": "public-administration",
      "name": "행정학과",
      "category": "사회계열"
    },
    {
      "id": "social-welfare",
      "name": "사회복지학과",
      "category": "사회계열"
    },
    {
      "id": "policy-studies",
      "name": "정책학과",
      "category": "사회계열"
    },
    {
      "id": "health-admin",
      "name": "보건행정학과",
      "category": "사회계열"
    },
    {
      "id": "consumer-studies",
      "name": "소비자학과",
      "category": "사회계열"
    }
  ],
  "분석": [
    {
      "id": "economics",
      "name": "경제학과",
      "category": "사회계열"
    },
    {
      "id": "policy-studies",
      "name": "정책학과",
      "category": "사회계열"
    }
  ],
  "회계사": [
    {
      "id": "accounting",
      "name": "회계학과",
      "category": "사회계열"
    }
  ],
  "세무": [
    {
      "id": "accounting",
      "name": "회계학과",
      "category": "사회계열"
    }
  ],
  "감사": [
    {
      "id": "accounting",
      "name": "회계학과",
      "category": "사회계열"
    }
  ],
  "CPA": [
    {
      "id": "accounting",
      "name": "회계학과",
      "category": "사회계열"
    }
  ],
  "법": [
    {
      "id": "law",
      "name": "법학과",
      "category": "사회계열"
    }
  ],
  "변호사": [
    {
      "id": "law",
      "name": "법학과",
      "category": "사회계열"
    }
  ],
  "로스쿨": [
    {
      "id": "law",
      "name": "법학과",
      "category": "사회계열"
    }
  ],
  "정의": [
    {
      "id": "law",
      "name": "법학과",
      "category": "사회계열"
    }
  ],
  "논리": [
    {
      "id": "law",
      "name": "법학과",
      "category": "사회계열"
    },
    {
      "id": "philosophy",
      "name": "철학과",
      "category": "인문계열"
    }
  ],
  "정치": [
    {
      "id": "political-science",
      "name": "정치외교학과",
      "category": "사회계열"
    }
  ],
  "외교": [
    {
      "id": "political-science",
      "name": "정치외교학과",
      "category": "사회계열"
    }
  ],
  "국제관계": [
    {
      "id": "political-science",
      "name": "정치외교학과",
      "category": "사회계열"
    },
    {
      "id": "global-studies",
      "name": "글로벌학과",
      "category": "사회계열"
    }
  ],
  "공직": [
    {
      "id": "political-science",
      "name": "정치외교학과",
      "category": "사회계열"
    },
    {
      "id": "public-administration",
      "name": "행정학과",
      "category": "사회계열"
    }
  ],
  "상담": [
    {
      "id": "psychology",
      "name": "심리학과",
      "category": "사회계열"
    },
    {
      "id": "social-welfare",
      "name": "사회복지학과",
      "category": "사회계열"
    },
    {
      "id": "family-studies",
      "name": "가족학과",
      "category": "사회계열"
    },
    {
      "id": "youth-studies",
      "name": "청소년학과",
      "category": "사회계열"
    }
  ],
  "인지": [
    {
      "id": "psychology",
      "name": "심리학과",
      "category": "사회계열"
    }
  ],
  "행동": [
    {
      "id": "psychology",
      "name": "심리학과",
      "category": "사회계열"
    }
  ],
  "사회구조": [
    {
      "id": "sociology",
      "name": "사회학과",
      "category": "사회계열"
    }
  ],
  "조사": [
    {
      "id": "sociology",
      "name": "사회학과",
      "category": "사회계열"
    }
  ],
  "문화": [
    {
      "id": "sociology",
      "name": "사회학과",
      "category": "사회계열"
    },
    {
      "id": "anthropology",
      "name": "문화인류학과",
      "category": "인문계열"
    }
  ],
  "교육": [
    {
      "id": "education",
      "name": "교육학과",
      "category": "교육계열"
    },
    {
      "id": "korean-language-edu",
      "name": "국어교육과",
      "category": "교육계열"
    },
    {
      "id": "mathematics",
      "name": "수학과",
      "category": "자연계열"
    }
  ],
  "학습": [
    {
      "id": "education",
      "name": "교육학과",
      "category": "교육계열"
    }
  ],
  "평생교육": [
    {
      "id": "education",
      "name": "교육학과",
      "category": "교육계열"
    }
  ],
  "심리": [
    {
      "id": "education",
      "name": "교육학과",
      "category": "교육계열"
    },
    {
      "id": "consumer-studies",
      "name": "소비자학과",
      "category": "사회계열"
    }
  ],
  "국어": [
    {
      "id": "korean-language-edu",
      "name": "국어교육과",
      "category": "교육계열"
    }
  ],
  "교사": [
    {
      "id": "korean-language-edu",
      "name": "국어교육과",
      "category": "교육계열"
    },
    {
      "id": "physical-education",
      "name": "체육교육과",
      "category": "교육계열"
    },
    {
      "id": "math-edu",
      "name": "수학교육과",
      "category": "교육계열"
    },
    {
      "id": "english-edu",
      "name": "영어교육과",
      "category": "교육계열"
    },
    {
      "id": "social-edu",
      "name": "사회교육과",
      "category": "교육계열"
    },
    {
      "id": "science-edu",
      "name": "과학교육과",
      "category": "교육계열"
    },
    {
      "id": "elementary-edu",
      "name": "초등교육과",
      "category": "교육계열"
    },
    {
      "id": "ethics-edu",
      "name": "윤리교육과",
      "category": "교육계열"
    },
    {
      "id": "art-edu",
      "name": "미술교육과",
      "category": "교육계열"
    },
    {
      "id": "music-edu",
      "name": "음악교육과",
      "category": "교육계열"
    },
    {
      "id": "technology-edu",
      "name": "기술교육과",
      "category": "교육계열"
    },
    {
      "id": "home-edu",
      "name": "가정교육과",
      "category": "교육계열"
    },
    {
      "id": "history-edu",
      "name": "역사교육과",
      "category": "교육계열"
    }
  ],
  "문학": [
    {
      "id": "korean-language-edu",
      "name": "국어교육과",
      "category": "교육계열"
    },
    {
      "id": "english-language-lit",
      "name": "영어영문학과",
      "category": "인문계열"
    },
    {
      "id": "korean-language-lit",
      "name": "국어국문학과",
      "category": "인문계열"
    },
    {
      "id": "french-lit",
      "name": "불어불문학과",
      "category": "인문계열"
    },
    {
      "id": "german-lit",
      "name": "독어독문학과",
      "category": "인문계열"
    },
    {
      "id": "japanese-lit",
      "name": "일어일문학과",
      "category": "인문계열"
    },
    {
      "id": "chinese-lit",
      "name": "중어중문학과",
      "category": "인문계열"
    },
    {
      "id": "russian-lit",
      "name": "노어노문학과",
      "category": "인문계열"
    },
    {
      "id": "spanish-lit",
      "name": "서어서문학과",
      "category": "인문계열"
    }
  ],
  "문법": [
    {
      "id": "korean-language-edu",
      "name": "국어교육과",
      "category": "교육계열"
    }
  ],
  "영어": [
    {
      "id": "english-language-lit",
      "name": "영어영문학과",
      "category": "인문계열"
    },
    {
      "id": "english-edu",
      "name": "영어교육과",
      "category": "교육계열"
    }
  ],
  "통번역": [
    {
      "id": "english-language-lit",
      "name": "영어영문학과",
      "category": "인문계열"
    },
    {
      "id": "french-lit",
      "name": "불어불문학과",
      "category": "인문계열"
    },
    {
      "id": "japanese-lit",
      "name": "일어일문학과",
      "category": "인문계열"
    },
    {
      "id": "chinese-lit",
      "name": "중어중문학과",
      "category": "인문계열"
    }
  ],
  "영미문화": [
    {
      "id": "english-language-lit",
      "name": "영어영문학과",
      "category": "인문계열"
    }
  ],
  "언어학": [
    {
      "id": "english-language-lit",
      "name": "영어영문학과",
      "category": "인문계열"
    }
  ],
  "국어학": [
    {
      "id": "korean-language-lit",
      "name": "국어국문학과",
      "category": "인문계열"
    }
  ],
  "출판": [
    {
      "id": "korean-language-lit",
      "name": "국어국문학과",
      "category": "인문계열"
    }
  ],
  "콘텐츠": [
    {
      "id": "korean-language-lit",
      "name": "국어국문학과",
      "category": "인문계열"
    },
    {
      "id": "media-communication",
      "name": "미디어커뮤니케이션학과",
      "category": "사회계열"
    },
    {
      "id": "japanese-lit",
      "name": "일어일문학과",
      "category": "인문계열"
    }
  ],
  "글쓰기": [
    {
      "id": "korean-language-lit",
      "name": "국어국문학과",
      "category": "인문계열"
    }
  ],
  "역사": [
    {
      "id": "history",
      "name": "사학과",
      "category": "인문계열"
    },
    {
      "id": "history-edu",
      "name": "역사교육과",
      "category": "교육계열"
    }
  ],
  "사료": [
    {
      "id": "history",
      "name": "사학과",
      "category": "인문계열"
    },
    {
      "id": "east-asian-history",
      "name": "동양사학과",
      "category": "인문계열"
    },
    {
      "id": "western-history",
      "name": "서양사학과",
      "category": "인문계열"
    }
  ],
  "문명": [
    {
      "id": "history",
      "name": "사학과",
      "category": "인문계열"
    }
  ],
  "고고학": [
    {
      "id": "history",
      "name": "사학과",
      "category": "인문계열"
    },
    {
      "id": "archaeology",
      "name": "고고학과",
      "category": "인문계열"
    }
  ],
  "박물관": [
    {
      "id": "history",
      "name": "사학과",
      "category": "인문계열"
    },
    {
      "id": "cultural-heritage",
      "name": "문화재학과",
      "category": "인문계열"
    }
  ],
  "철학": [
    {
      "id": "philosophy",
      "name": "철학과",
      "category": "인문계열"
    },
    {
      "id": "german-lit",
      "name": "독어독문학과",
      "category": "인문계열"
    }
  ],
  "윤리": [
    {
      "id": "philosophy",
      "name": "철학과",
      "category": "인문계열"
    },
    {
      "id": "ethics-edu",
      "name": "윤리교육과",
      "category": "교육계열"
    }
  ],
  "사상": [
    {
      "id": "philosophy",
      "name": "철학과",
      "category": "인문계열"
    },
    {
      "id": "religion-studies",
      "name": "종교학과",
      "category": "인문계열"
    }
  ],
  "비판적사고": [
    {
      "id": "philosophy",
      "name": "철학과",
      "category": "인문계열"
    }
  ],
  "분자생물학": [
    {
      "id": "biology",
      "name": "생명과학과",
      "category": "자연계열"
    }
  ],
  "유전": [
    {
      "id": "biology",
      "name": "생명과학과",
      "category": "자연계열"
    }
  ],
  "생태": [
    {
      "id": "biology",
      "name": "생명과학과",
      "category": "자연계열"
    },
    {
      "id": "oceanography",
      "name": "해양학과",
      "category": "자연계열"
    },
    {
      "id": "forestry",
      "name": "산림학과",
      "category": "자연계열"
    }
  ],
  "의학": [
    {
      "id": "biology",
      "name": "생명과학과",
      "category": "자연계열"
    }
  ],
  "유기화학": [
    {
      "id": "chemistry",
      "name": "화학과",
      "category": "자연계열"
    }
  ],
  "분석화학": [
    {
      "id": "chemistry",
      "name": "화학과",
      "category": "자연계열"
    }
  ],
  "실험": [
    {
      "id": "chemistry",
      "name": "화학과",
      "category": "자연계열"
    }
  ],
  "수학": [
    {
      "id": "mathematics",
      "name": "수학과",
      "category": "자연계열"
    },
    {
      "id": "math-edu",
      "name": "수학교육과",
      "category": "교육계열"
    }
  ],
  "보험": [
    {
      "id": "mathematics",
      "name": "수학과",
      "category": "자연계열"
    }
  ],
  "양자역학": [
    {
      "id": "physics",
      "name": "물리학과",
      "category": "자연계열"
    }
  ],
  "전자기학": [
    {
      "id": "physics",
      "name": "물리학과",
      "category": "자연계열"
    }
  ],
  "이론물리": [
    {
      "id": "physics",
      "name": "물리학과",
      "category": "자연계열"
    }
  ],
  "연구": [
    {
      "id": "physics",
      "name": "물리학과",
      "category": "자연계열"
    }
  ],
  "UX": [
    {
      "id": "design",
      "name": "디자인학과",
      "category": "예체능계열"
    },
    {
      "id": "industrial-design-eng",
      "name": "산업디자인공학과",
      "category": "공학계열"
    },
    {
      "id": "visual-design",
      "name": "시각디자인학과",
      "category": "예체능계열"
    }
  ],
  "그래픽": [
    {
      "id": "design",
      "name": "디자인학과",
      "category": "예체능계열"
    }
  ],
  "브랜드": [
    {
      "id": "design",
      "name": "디자인학과",
      "category": "예체능계열"
    },
    {
      "id": "visual-design",
      "name": "시각디자인학과",
      "category": "예체능계열"
    }
  ],
  "산업디자인": [
    {
      "id": "design",
      "name": "디자인학과",
      "category": "예체능계열"
    },
    {
      "id": "industrial-design-eng",
      "name": "산업디자인공학과",
      "category": "공학계열"
    }
  ],
  "포트폴리오": [
    {
      "id": "design",
      "name": "디자인학과",
      "category": "예체능계열"
    }
  ],
  "미디어": [
    {
      "id": "media-communication",
      "name": "미디어커뮤니케이션학과",
      "category": "사회계열"
    }
  ],
  "저널리즘": [
    {
      "id": "media-communication",
      "name": "미디어커뮤니케이션학과",
      "category": "사회계열"
    },
    {
      "id": "broadcasting",
      "name": "신문방송학과",
      "category": "사회계열"
    }
  ],
  "광고": [
    {
      "id": "media-communication",
      "name": "미디어커뮤니케이션학과",
      "category": "사회계열"
    },
    {
      "id": "advertising",
      "name": "광고홍보학과",
      "category": "사회계열"
    }
  ],
  "PR": [
    {
      "id": "media-communication",
      "name": "미디어커뮤니케이션학과",
      "category": "사회계열"
    },
    {
      "id": "advertising",
      "name": "광고홍보학과",
      "category": "사회계열"
    }
  ],
  "체육": [
    {
      "id": "physical-education",
      "name": "체육교육과",
      "category": "교육계열"
    }
  ],
  "스포츠": [
    {
      "id": "physical-education",
      "name": "체육교육과",
      "category": "교육계열"
    },
    {
      "id": "sports-science",
      "name": "스포츠과학과",
      "category": "예체능계열"
    }
  ],
  "운동과학": [
    {
      "id": "physical-education",
      "name": "체육교육과",
      "category": "교육계열"
    },
    {
      "id": "sports-science",
      "name": "스포츠과학과",
      "category": "예체능계열"
    }
  ],
  "코칭": [
    {
      "id": "physical-education",
      "name": "체육교육과",
      "category": "교육계열"
    }
  ],
  "프랑스어": [
    {
      "id": "french-lit",
      "name": "불어불문학과",
      "category": "인문계열"
    }
  ],
  "유럽": [
    {
      "id": "french-lit",
      "name": "불어불문학과",
      "category": "인문계열"
    },
    {
      "id": "german-lit",
      "name": "독어독문학과",
      "category": "인문계열"
    },
    {
      "id": "western-history",
      "name": "서양사학과",
      "category": "인문계열"
    }
  ],
  "독일어": [
    {
      "id": "german-lit",
      "name": "독어독문학과",
      "category": "인문계열"
    }
  ],
  "일본어": [
    {
      "id": "japanese-lit",
      "name": "일어일문학과",
      "category": "인문계열"
    }
  ],
  "중국어": [
    {
      "id": "chinese-lit",
      "name": "중어중문학과",
      "category": "인문계열"
    }
  ],
  "동양사상": [
    {
      "id": "chinese-lit",
      "name": "중어중문학과",
      "category": "인문계열"
    }
  ],
  "러시아어": [
    {
      "id": "russian-lit",
      "name": "노어노문학과",
      "category": "인문계열"
    }
  ],
  "유라시아": [
    {
      "id": "russian-lit",
      "name": "노어노문학과",
      "category": "인문계열"
    }
  ],
  "스페인어": [
    {
      "id": "spanish-lit",
      "name": "서어서문학과",
      "category": "인문계열"
    }
  ],
  "라틴아메리카": [
    {
      "id": "spanish-lit",
      "name": "서어서문학과",
      "category": "인문계열"
    }
  ],
  "아랍어": [
    {
      "id": "arabic-lit",
      "name": "아랍어과",
      "category": "인문계열"
    }
  ],
  "중동": [
    {
      "id": "arabic-lit",
      "name": "아랍어과",
      "category": "인문계열"
    }
  ],
  "이슬람": [
    {
      "id": "arabic-lit",
      "name": "아랍어과",
      "category": "인문계열"
    }
  ],
  "베트남어": [
    {
      "id": "vietnamese-lit",
      "name": "베트남어과",
      "category": "인문계열"
    }
  ],
  "동남아": [
    {
      "id": "vietnamese-lit",
      "name": "베트남어과",
      "category": "인문계열"
    }
  ],
  "무역": [
    {
      "id": "vietnamese-lit",
      "name": "베트남어과",
      "category": "인문계열"
    },
    {
      "id": "trade",
      "name": "무역학과",
      "category": "사회계열"
    }
  ],
  "힌디어": [
    {
      "id": "indian-lit",
      "name": "인도학과",
      "category": "인문계열"
    }
  ],
  "인도": [
    {
      "id": "indian-lit",
      "name": "인도학과",
      "category": "인문계열"
    }
  ],
  "종교": [
    {
      "id": "indian-lit",
      "name": "인도학과",
      "category": "인문계열"
    },
    {
      "id": "religion-studies",
      "name": "종교학과",
      "category": "인문계열"
    }
  ],
  "동양사": [
    {
      "id": "east-asian-history",
      "name": "동양사학과",
      "category": "인문계열"
    }
  ],
  "중국사": [
    {
      "id": "east-asian-history",
      "name": "동양사학과",
      "category": "인문계열"
    }
  ],
  "서양사": [
    {
      "id": "western-history",
      "name": "서양사학과",
      "category": "인문계열"
    }
  ],
  "유적": [
    {
      "id": "archaeology",
      "name": "고고학과",
      "category": "인문계열"
    }
  ],
  "발굴": [
    {
      "id": "archaeology",
      "name": "고고학과",
      "category": "인문계열"
    }
  ],
  "문화재": [
    {
      "id": "archaeology",
      "name": "고고학과",
      "category": "인문계열"
    },
    {
      "id": "cultural-heritage",
      "name": "문화재학과",
      "category": "인문계열"
    }
  ],
  "복원": [
    {
      "id": "cultural-heritage",
      "name": "문화재학과",
      "category": "인문계열"
    }
  ],
  "보존": [
    {
      "id": "cultural-heritage",
      "name": "문화재학과",
      "category": "인문계열"
    }
  ],
  "비교": [
    {
      "id": "religion-studies",
      "name": "종교학과",
      "category": "인문계열"
    }
  ],
  "신학": [
    {
      "id": "theology",
      "name": "신학과",
      "category": "인문계열"
    }
  ],
  "성서": [
    {
      "id": "theology",
      "name": "신학과",
      "category": "인문계열"
    }
  ],
  "기독교": [
    {
      "id": "theology",
      "name": "신학과",
      "category": "인문계열"
    }
  ],
  "인류학": [
    {
      "id": "anthropology",
      "name": "문화인류학과",
      "category": "인문계열"
    }
  ],
  "민족지": [
    {
      "id": "anthropology",
      "name": "문화인류학과",
      "category": "인문계열"
    }
  ],
  "행정": [
    {
      "id": "public-administration",
      "name": "행정학과",
      "category": "사회계열"
    }
  ],
  "통상": [
    {
      "id": "trade",
      "name": "무역학과",
      "category": "사회계열"
    },
    {
      "id": "international-business",
      "name": "국제통상학과",
      "category": "사회계열"
    }
  ],
  "국제경영": [
    {
      "id": "international-business",
      "name": "국제통상학과",
      "category": "사회계열"
    }
  ],
  "다국적": [
    {
      "id": "international-business",
      "name": "국제통상학과",
      "category": "사회계열"
    }
  ],
  "호텔": [
    {
      "id": "hotel-management",
      "name": "호텔경영학과",
      "category": "사회계열"
    }
  ],
  "외식": [
    {
      "id": "hotel-management",
      "name": "호텔경영학과",
      "category": "사회계열"
    }
  ],
  "서비스": [
    {
      "id": "hotel-management",
      "name": "호텔경영학과",
      "category": "사회계열"
    }
  ],
  "관광": [
    {
      "id": "tourism",
      "name": "관광경영학과",
      "category": "사회계열"
    }
  ],
  "여행": [
    {
      "id": "tourism",
      "name": "관광경영학과",
      "category": "사회계열"
    }
  ],
  "문화관광": [
    {
      "id": "tourism",
      "name": "관광경영학과",
      "category": "사회계열"
    }
  ],
  "부동산": [
    {
      "id": "real-estate",
      "name": "부동산학과",
      "category": "사회계열"
    }
  ],
  "감정평가": [
    {
      "id": "real-estate",
      "name": "부동산학과",
      "category": "사회계열"
    }
  ],
  "도시정책": [
    {
      "id": "real-estate",
      "name": "부동산학과",
      "category": "사회계열"
    }
  ],
  "디지털 마케팅": [
    {
      "id": "advertising",
      "name": "광고홍보학과",
      "category": "사회계열"
    }
  ],
  "사회복지": [
    {
      "id": "social-welfare",
      "name": "사회복지학과",
      "category": "사회계열"
    }
  ],
  "아동": [
    {
      "id": "child-studies",
      "name": "아동학과",
      "category": "사회계열"
    }
  ],
  "발달": [
    {
      "id": "child-studies",
      "name": "아동학과",
      "category": "사회계열"
    }
  ],
  "보육": [
    {
      "id": "child-studies",
      "name": "아동학과",
      "category": "사회계열"
    },
    {
      "id": "early-childhood-edu",
      "name": "유아교육과",
      "category": "교육계열"
    }
  ],
  "가족": [
    {
      "id": "family-studies",
      "name": "가족학과",
      "category": "사회계열"
    }
  ],
  "결혼": [
    {
      "id": "family-studies",
      "name": "가족학과",
      "category": "사회계열"
    }
  ],
  "청소년": [
    {
      "id": "youth-studies",
      "name": "청소년학과",
      "category": "사회계열"
    }
  ],
  "지도사": [
    {
      "id": "youth-studies",
      "name": "청소년학과",
      "category": "사회계열"
    }
  ],
  "평가": [
    {
      "id": "policy-studies",
      "name": "정책학과",
      "category": "사회계열"
    }
  ],
  "방송": [
    {
      "id": "broadcasting",
      "name": "신문방송학과",
      "category": "사회계열"
    }
  ],
  "PD": [
    {
      "id": "broadcasting",
      "name": "신문방송학과",
      "category": "사회계열"
    }
  ],
  "경찰": [
    {
      "id": "police-admin",
      "name": "경찰행정학과",
      "category": "사회계열"
    }
  ],
  "범죄학": [
    {
      "id": "police-admin",
      "name": "경찰행정학과",
      "category": "사회계열"
    }
  ],
  "형사정책": [
    {
      "id": "police-admin",
      "name": "경찰행정학과",
      "category": "사회계열"
    }
  ],
  "군사": [
    {
      "id": "military-studies",
      "name": "군사학과",
      "category": "사회계열"
    }
  ],
  "안보": [
    {
      "id": "military-studies",
      "name": "군사학과",
      "category": "사회계열"
    },
    {
      "id": "north-korea-studies",
      "name": "북한학과",
      "category": "사회계열"
    }
  ],
  "국방": [
    {
      "id": "military-studies",
      "name": "군사학과",
      "category": "사회계열"
    }
  ],
  "보건": [
    {
      "id": "health-admin",
      "name": "보건행정학과",
      "category": "사회계열"
    },
    {
      "id": "public-health",
      "name": "보건학과",
      "category": "의약계열"
    }
  ],
  "의료 경영": [
    {
      "id": "health-admin",
      "name": "보건행정학과",
      "category": "사회계열"
    }
  ],
  "지방자치": [
    {
      "id": "urban-planning-social",
      "name": "도시행정학과",
      "category": "사회계열"
    }
  ],
  "지역개발": [
    {
      "id": "urban-planning-social",
      "name": "도시행정학과",
      "category": "사회계열"
    }
  ],
  "지리": [
    {
      "id": "human-geography",
      "name": "지리학과",
      "category": "사회계열"
    }
  ],
  "GIS": [
    {
      "id": "human-geography",
      "name": "지리학과",
      "category": "사회계열"
    },
    {
      "id": "urban-planning-eng",
      "name": "도시공학과",
      "category": "공학계열"
    }
  ],
  "지역연구": [
    {
      "id": "global-studies",
      "name": "글로벌학과",
      "category": "사회계열"
    }
  ],
  "외국어": [
    {
      "id": "global-studies",
      "name": "글로벌학과",
      "category": "사회계열"
    }
  ],
  "북한": [
    {
      "id": "north-korea-studies",
      "name": "북한학과",
      "category": "사회계열"
    }
  ],
  "통일": [
    {
      "id": "north-korea-studies",
      "name": "북한학과",
      "category": "사회계열"
    }
  ],
  "소비자": [
    {
      "id": "consumer-studies",
      "name": "소비자학과",
      "category": "사회계열"
    }
  ],
  "임용": [
    {
      "id": "math-edu",
      "name": "수학교육과",
      "category": "교육계열"
    },
    {
      "id": "english-edu",
      "name": "영어교육과",
      "category": "교육계열"
    },
    {
      "id": "social-edu",
      "name": "사회교육과",
      "category": "교육계열"
    },
    {
      "id": "science-edu",
      "name": "과학교육과",
      "category": "교육계열"
    },
    {
      "id": "history-edu",
      "name": "역사교육과",
      "category": "교육계열"
    }
  ],
  "사회": [
    {
      "id": "social-edu",
      "name": "사회교육과",
      "category": "교육계열"
    }
  ],
  "과학": [
    {
      "id": "science-edu",
      "name": "과학교육과",
      "category": "교육계열"
    }
  ],
  "유아": [
    {
      "id": "early-childhood-edu",
      "name": "유아교육과",
      "category": "교육계열"
    }
  ],
  "유치원": [
    {
      "id": "early-childhood-edu",
      "name": "유아교육과",
      "category": "교육계열"
    }
  ],
  "초등": [
    {
      "id": "elementary-edu",
      "name": "초등교육과",
      "category": "교육계열"
    }
  ],
  "교대": [
    {
      "id": "elementary-edu",
      "name": "초등교육과",
      "category": "교육계열"
    }
  ],
  "특수교육": [
    {
      "id": "special-edu",
      "name": "특수교육과",
      "category": "교육계열"
    }
  ],
  "장애": [
    {
      "id": "special-edu",
      "name": "특수교육과",
      "category": "교육계열"
    }
  ],
  "통합교육": [
    {
      "id": "special-edu",
      "name": "특수교육과",
      "category": "교육계열"
    }
  ],
  "도덕": [
    {
      "id": "ethics-edu",
      "name": "윤리교육과",
      "category": "교육계열"
    }
  ],
  "미술": [
    {
      "id": "art-edu",
      "name": "미술교육과",
      "category": "교육계열"
    }
  ],
  "실기": [
    {
      "id": "art-edu",
      "name": "미술교육과",
      "category": "교육계열"
    },
    {
      "id": "music-edu",
      "name": "음악교육과",
      "category": "교육계열"
    }
  ],
  "음악": [
    {
      "id": "music-edu",
      "name": "음악교육과",
      "category": "교육계열"
    }
  ],
  "기술": [
    {
      "id": "technology-edu",
      "name": "기술교육과",
      "category": "교육계열"
    }
  ],
  "공작": [
    {
      "id": "technology-edu",
      "name": "기술교육과",
      "category": "교육계열"
    }
  ],
  "가정": [
    {
      "id": "home-edu",
      "name": "가정교육과",
      "category": "교육계열"
    }
  ],
  "식품": [
    {
      "id": "home-edu",
      "name": "가정교육과",
      "category": "교육계열"
    },
    {
      "id": "food-engineering",
      "name": "식품공학과",
      "category": "공학계열"
    }
  ],
  "네트워크": [
    {
      "id": "information-communication",
      "name": "정보통신공학과",
      "category": "공학계열"
    }
  ],
  "신호처리": [
    {
      "id": "information-communication",
      "name": "정보통신공학과",
      "category": "공학계열"
    }
  ],
  "DevOps": [
    {
      "id": "software",
      "name": "소프트웨어공학과",
      "category": "공학계열"
    }
  ],
  "클라우드": [
    {
      "id": "software",
      "name": "소프트웨어공학과",
      "category": "공학계열"
    }
  ],
  "딥러닝": [
    {
      "id": "ai-engineering",
      "name": "인공지능학과",
      "category": "공학계열"
    }
  ],
  "NLP": [
    {
      "id": "ai-engineering",
      "name": "인공지능학과",
      "category": "공학계열"
    }
  ],
  "빅데이터": [
    {
      "id": "data-science",
      "name": "데이터사이언스학과",
      "category": "공학계열"
    }
  ],
  "보안": [
    {
      "id": "cybersecurity",
      "name": "사이버보안학과",
      "category": "공학계열"
    }
  ],
  "암호": [
    {
      "id": "cybersecurity",
      "name": "사이버보안학과",
      "category": "공학계열"
    }
  ],
  "포렌식": [
    {
      "id": "cybersecurity",
      "name": "사이버보안학과",
      "category": "공학계열"
    }
  ],
  "게임": [
    {
      "id": "game-engineering",
      "name": "게임공학과",
      "category": "공학계열"
    },
    {
      "id": "game-graphics",
      "name": "게임그래픽디자인학과",
      "category": "예체능계열"
    }
  ],
  "그래픽스": [
    {
      "id": "game-engineering",
      "name": "게임공학과",
      "category": "공학계열"
    }
  ],
  "엔진": [
    {
      "id": "game-engineering",
      "name": "게임공학과",
      "category": "공학계열"
    }
  ],
  "항공": [
    {
      "id": "aerospace",
      "name": "항공우주공학과",
      "category": "공학계열"
    }
  ],
  "우주": [
    {
      "id": "aerospace",
      "name": "항공우주공학과",
      "category": "공학계열"
    },
    {
      "id": "astronomy",
      "name": "천문우주학과",
      "category": "자연계열"
    }
  ],
  "추진": [
    {
      "id": "aerospace",
      "name": "항공우주공학과",
      "category": "공학계열"
    }
  ],
  "조선": [
    {
      "id": "naval-architecture",
      "name": "조선해양공학과",
      "category": "공학계열"
    }
  ],
  "해양": [
    {
      "id": "naval-architecture",
      "name": "조선해양공학과",
      "category": "공학계열"
    },
    {
      "id": "ocean-engineering",
      "name": "해양공학과",
      "category": "공학계열"
    },
    {
      "id": "oceanography",
      "name": "해양학과",
      "category": "자연계열"
    }
  ],
  "선박": [
    {
      "id": "naval-architecture",
      "name": "조선해양공학과",
      "category": "공학계열"
    }
  ],
  "전기차": [
    {
      "id": "automotive",
      "name": "자동차공학과",
      "category": "공학계열"
    }
  ],
  "자율주행": [
    {
      "id": "automotive",
      "name": "자동차공학과",
      "category": "공학계열"
    }
  ],
  "기계전자": [
    {
      "id": "mechatronics",
      "name": "메카트로닉스공학과",
      "category": "공학계열"
    }
  ],
  "스마트팩토리": [
    {
      "id": "mechatronics",
      "name": "메카트로닉스공학과",
      "category": "공학계열"
    }
  ],
  "배터리": [
    {
      "id": "new-materials",
      "name": "신소재공학과",
      "category": "공학계열"
    }
  ],
  "금속": [
    {
      "id": "metallurgy",
      "name": "금속재료공학과",
      "category": "공학계열"
    }
  ],
  "철강": [
    {
      "id": "metallurgy",
      "name": "금속재료공학과",
      "category": "공학계열"
    }
  ],
  "합금": [
    {
      "id": "metallurgy",
      "name": "금속재료공학과",
      "category": "공학계열"
    }
  ],
  "섬유": [
    {
      "id": "textile",
      "name": "섬유공학과",
      "category": "공학계열"
    }
  ],
  "고분자": [
    {
      "id": "textile",
      "name": "섬유공학과",
      "category": "공학계열"
    }
  ],
  "텍스타일": [
    {
      "id": "textile",
      "name": "섬유공학과",
      "category": "공학계열"
    }
  ],
  "발효": [
    {
      "id": "food-engineering",
      "name": "식품공학과",
      "category": "공학계열"
    }
  ],
  "가공": [
    {
      "id": "food-engineering",
      "name": "식품공학과",
      "category": "공학계열"
    }
  ],
  "환경": [
    {
      "id": "environmental",
      "name": "환경공학과",
      "category": "공학계열"
    }
  ],
  "수질": [
    {
      "id": "environmental",
      "name": "환경공학과",
      "category": "공학계열"
    }
  ],
  "탄소중립": [
    {
      "id": "environmental",
      "name": "환경공학과",
      "category": "공학계열"
    }
  ],
  "토목": [
    {
      "id": "civil-construction",
      "name": "토목공학과",
      "category": "공학계열"
    }
  ],
  "건설": [
    {
      "id": "civil-construction",
      "name": "토목공학과",
      "category": "공학계열"
    }
  ],
  "인프라": [
    {
      "id": "civil-construction",
      "name": "토목공학과",
      "category": "공학계열"
    }
  ],
  "도시계획": [
    {
      "id": "urban-planning-eng",
      "name": "도시공학과",
      "category": "공학계열"
    }
  ],
  "교통": [
    {
      "id": "urban-planning-eng",
      "name": "도시공학과",
      "category": "공학계열"
    },
    {
      "id": "transportation",
      "name": "교통공학과",
      "category": "공학계열"
    }
  ],
  "ITS": [
    {
      "id": "transportation",
      "name": "교통공학과",
      "category": "공학계열"
    }
  ],
  "시스템": [
    {
      "id": "systems",
      "name": "시스템공학과",
      "category": "공학계열"
    }
  ],
  "신뢰성": [
    {
      "id": "systems",
      "name": "시스템공학과",
      "category": "공학계열"
    }
  ],
  "통합": [
    {
      "id": "systems",
      "name": "시스템공학과",
      "category": "공학계열"
    }
  ],
  "원자력": [
    {
      "id": "nuclear",
      "name": "원자력공학과",
      "category": "공학계열"
    }
  ],
  "방사선": [
    {
      "id": "nuclear",
      "name": "원자력공학과",
      "category": "공학계열"
    },
    {
      "id": "radiology",
      "name": "방사선학과",
      "category": "의약계열"
    }
  ],
  "핵연료": [
    {
      "id": "nuclear",
      "name": "원자력공학과",
      "category": "공학계열"
    }
  ],
  "신재생": [
    {
      "id": "energy",
      "name": "에너지공학과",
      "category": "공학계열"
    },
    {
      "id": "ocean-engineering",
      "name": "해양공학과",
      "category": "공학계열"
    }
  ],
  "수소": [
    {
      "id": "energy",
      "name": "에너지공학과",
      "category": "공학계열"
    }
  ],
  "나노": [
    {
      "id": "nano",
      "name": "나노공학과",
      "category": "공학계열"
    }
  ],
  "소재": [
    {
      "id": "nano",
      "name": "나노공학과",
      "category": "공학계열"
    }
  ],
  "유전공학": [
    {
      "id": "bio-engineering",
      "name": "생명공학과",
      "category": "공학계열"
    }
  ],
  "세포": [
    {
      "id": "bio-engineering",
      "name": "생명공학과",
      "category": "공학계열"
    }
  ],
  "인간공학": [
    {
      "id": "industrial-design-eng",
      "name": "산업디자인공학과",
      "category": "공학계열"
    }
  ],
  "자원": [
    {
      "id": "mining",
      "name": "자원공학과",
      "category": "공학계열"
    }
  ],
  "광물": [
    {
      "id": "mining",
      "name": "자원공학과",
      "category": "공학계열"
    }
  ],
  "시추": [
    {
      "id": "mining",
      "name": "자원공학과",
      "category": "공학계열"
    }
  ],
  "스마트팜": [
    {
      "id": "agricultural-engineering",
      "name": "농업생명공학과",
      "category": "공학계열"
    }
  ],
  "농업": [
    {
      "id": "agricultural-engineering",
      "name": "농업생명공학과",
      "category": "공학계열"
    },
    {
      "id": "agriculture",
      "name": "농학과",
      "category": "자연계열"
    }
  ],
  "생명공학": [
    {
      "id": "agricultural-engineering",
      "name": "농업생명공학과",
      "category": "공학계열"
    }
  ],
  "심해": [
    {
      "id": "ocean-engineering",
      "name": "해양공학과",
      "category": "공학계열"
    }
  ],
  "지구": [
    {
      "id": "earth-science",
      "name": "지구과학과",
      "category": "자연계열"
    }
  ],
  "기후": [
    {
      "id": "earth-science",
      "name": "지구과학과",
      "category": "자연계열"
    },
    {
      "id": "atmospheric",
      "name": "대기과학과",
      "category": "자연계열"
    }
  ],
  "지질": [
    {
      "id": "earth-science",
      "name": "지구과학과",
      "category": "자연계열"
    },
    {
      "id": "geology",
      "name": "지질학과",
      "category": "자연계열"
    }
  ],
  "천문": [
    {
      "id": "astronomy",
      "name": "천문우주학과",
      "category": "자연계열"
    }
  ],
  "관측": [
    {
      "id": "astronomy",
      "name": "천문우주학과",
      "category": "자연계열"
    }
  ],
  "확률": [
    {
      "id": "statistics",
      "name": "통계학과",
      "category": "자연계열"
    }
  ],
  "기상": [
    {
      "id": "atmospheric",
      "name": "대기과학과",
      "category": "자연계열"
    }
  ],
  "대기": [
    {
      "id": "atmospheric",
      "name": "대기과학과",
      "category": "자연계열"
    }
  ],
  "해류": [
    {
      "id": "oceanography",
      "name": "해양학과",
      "category": "자연계열"
    }
  ],
  "암석": [
    {
      "id": "geology",
      "name": "지질학과",
      "category": "자연계열"
    }
  ],
  "지층": [
    {
      "id": "geology",
      "name": "지질학과",
      "category": "자연계열"
    }
  ],
  "작물": [
    {
      "id": "agriculture",
      "name": "농학과",
      "category": "자연계열"
    }
  ],
  "토양": [
    {
      "id": "agriculture",
      "name": "농학과",
      "category": "자연계열"
    }
  ],
  "산림": [
    {
      "id": "forestry",
      "name": "산림학과",
      "category": "자연계열"
    }
  ],
  "임업": [
    {
      "id": "forestry",
      "name": "산림학과",
      "category": "자연계열"
    }
  ],
  "원예": [
    {
      "id": "horticulture",
      "name": "원예학과",
      "category": "자연계열"
    }
  ],
  "채소": [
    {
      "id": "horticulture",
      "name": "원예학과",
      "category": "자연계열"
    }
  ],
  "조경": [
    {
      "id": "horticulture",
      "name": "원예학과",
      "category": "자연계열"
    }
  ],
  "축산": [
    {
      "id": "animal-science",
      "name": "동물자원학과",
      "category": "자연계열"
    }
  ],
  "영양": [
    {
      "id": "animal-science",
      "name": "동물자원학과",
      "category": "자연계열"
    }
  ],
  "동물": [
    {
      "id": "animal-science",
      "name": "동물자원학과",
      "category": "자연계열"
    },
    {
      "id": "veterinary",
      "name": "수의예과",
      "category": "의약계열"
    }
  ],
  "수산": [
    {
      "id": "fisheries",
      "name": "수산생명의학과",
      "category": "자연계열"
    }
  ],
  "양식": [
    {
      "id": "fisheries",
      "name": "수산생명의학과",
      "category": "자연계열"
    }
  ],
  "어병학": [
    {
      "id": "fisheries",
      "name": "수산생명의학과",
      "category": "자연계열"
    }
  ],
  "치과": [
    {
      "id": "dentistry",
      "name": "치의예과",
      "category": "의약계열"
    }
  ],
  "구강": [
    {
      "id": "dentistry",
      "name": "치의예과",
      "category": "의약계열"
    }
  ],
  "한의학": [
    {
      "id": "korean-medicine",
      "name": "한의예과",
      "category": "의약계열"
    }
  ],
  "본초": [
    {
      "id": "korean-medicine",
      "name": "한의예과",
      "category": "의약계열"
    }
  ],
  "침구": [
    {
      "id": "korean-medicine",
      "name": "한의예과",
      "category": "의약계열"
    }
  ],
  "수의사": [
    {
      "id": "veterinary",
      "name": "수의예과",
      "category": "의약계열"
    }
  ],
  "검사": [
    {
      "id": "clinical-pathology",
      "name": "임상병리학과",
      "category": "의약계열"
    }
  ],
  "병리": [
    {
      "id": "clinical-pathology",
      "name": "임상병리학과",
      "category": "의약계열"
    }
  ],
  "혈액": [
    {
      "id": "clinical-pathology",
      "name": "임상병리학과",
      "category": "의약계열"
    }
  ],
  "영상진단": [
    {
      "id": "radiology",
      "name": "방사선학과",
      "category": "의약계열"
    }
  ],
  "MRI": [
    {
      "id": "radiology",
      "name": "방사선학과",
      "category": "의약계열"
    }
  ],
  "작업치료": [
    {
      "id": "occupational-therapy",
      "name": "작업치료학과",
      "category": "의약계열"
    }
  ],
  "노인": [
    {
      "id": "occupational-therapy",
      "name": "작업치료학과",
      "category": "의약계열"
    }
  ],
  "물리치료": [
    {
      "id": "physical-therapy",
      "name": "물리치료학과",
      "category": "의약계열"
    }
  ],
  "운동치료": [
    {
      "id": "physical-therapy",
      "name": "물리치료학과",
      "category": "의약계열"
    }
  ],
  "응급": [
    {
      "id": "emergency-medical",
      "name": "응급구조학과",
      "category": "의약계열"
    }
  ],
  "심폐소생": [
    {
      "id": "emergency-medical",
      "name": "응급구조학과",
      "category": "의약계열"
    }
  ],
  "시각디자인": [
    {
      "id": "visual-design",
      "name": "시각디자인학과",
      "category": "예체능계열"
    }
  ],
  "제품": [
    {
      "id": "industrial-design",
      "name": "산업디자인학과",
      "category": "예체능계열"
    }
  ],
  "운송": [
    {
      "id": "industrial-design",
      "name": "산업디자인학과",
      "category": "예체능계열"
    }
  ],
  "가전": [
    {
      "id": "industrial-design",
      "name": "산업디자인학과",
      "category": "예체능계열"
    }
  ],
  "패션": [
    {
      "id": "fashion-design",
      "name": "패션디자인학과",
      "category": "예체능계열"
    }
  ],
  "의상": [
    {
      "id": "fashion-design",
      "name": "패션디자인학과",
      "category": "예체능계열"
    }
  ],
  "MD": [
    {
      "id": "fashion-design",
      "name": "패션디자인학과",
      "category": "예체능계열"
    }
  ],
  "인테리어": [
    {
      "id": "interior-design",
      "name": "실내건축디자인학과",
      "category": "예체능계열"
    }
  ],
  "조명": [
    {
      "id": "interior-design",
      "name": "실내건축디자인학과",
      "category": "예체능계열"
    }
  ],
  "동양화": [
    {
      "id": "painting-eastern",
      "name": "동양화과",
      "category": "예체능계열"
    }
  ],
  "수묵": [
    {
      "id": "painting-eastern",
      "name": "동양화과",
      "category": "예체능계열"
    }
  ],
  "전통": [
    {
      "id": "painting-eastern",
      "name": "동양화과",
      "category": "예체능계열"
    }
  ],
  "회화": [
    {
      "id": "painting-western",
      "name": "서양화과",
      "category": "예체능계열"
    }
  ],
  "유화": [
    {
      "id": "painting-western",
      "name": "서양화과",
      "category": "예체능계열"
    }
  ],
  "현대미술": [
    {
      "id": "painting-western",
      "name": "서양화과",
      "category": "예체능계열"
    }
  ],
  "조각": [
    {
      "id": "sculpture",
      "name": "조소과",
      "category": "예체능계열"
    }
  ],
  "설치": [
    {
      "id": "sculpture",
      "name": "조소과",
      "category": "예체능계열"
    }
  ],
  "공공미술": [
    {
      "id": "sculpture",
      "name": "조소과",
      "category": "예체능계열"
    }
  ],
  "도자기": [
    {
      "id": "ceramic-art",
      "name": "도예과",
      "category": "예체능계열"
    }
  ],
  "세라믹": [
    {
      "id": "ceramic-art",
      "name": "도예과",
      "category": "예체능계열"
    }
  ],
  "공예": [
    {
      "id": "ceramic-art",
      "name": "도예과",
      "category": "예체능계열"
    }
  ],
  "사진": [
    {
      "id": "photography",
      "name": "사진학과",
      "category": "예체능계열"
    }
  ],
  "이미지": [
    {
      "id": "photography",
      "name": "사진학과",
      "category": "예체능계열"
    }
  ],
  "다큐": [
    {
      "id": "photography",
      "name": "사진학과",
      "category": "예체능계열"
    }
  ],
  "영화": [
    {
      "id": "film-tv",
      "name": "영화영상학과",
      "category": "예체능계열"
    },
    {
      "id": "theater-film",
      "name": "연극영화학과",
      "category": "예체능계열"
    }
  ],
  "연출": [
    {
      "id": "film-tv",
      "name": "영화영상학과",
      "category": "예체능계열"
    }
  ],
  "만화": [
    {
      "id": "animation",
      "name": "만화애니메이션학과",
      "category": "예체능계열"
    }
  ],
  "애니메이션": [
    {
      "id": "animation",
      "name": "만화애니메이션학과",
      "category": "예체능계열"
    }
  ],
  "웹툰": [
    {
      "id": "animation",
      "name": "만화애니메이션학과",
      "category": "예체능계열"
    }
  ],
  "캐릭터": [
    {
      "id": "game-graphics",
      "name": "게임그래픽디자인학과",
      "category": "예체능계열"
    }
  ],
  "3D": [
    {
      "id": "game-graphics",
      "name": "게임그래픽디자인학과",
      "category": "예체능계열"
    }
  ],
  "음악이론": [
    {
      "id": "music-theory",
      "name": "음악학과",
      "category": "예체능계열"
    }
  ],
  "음악사": [
    {
      "id": "music-theory",
      "name": "음악학과",
      "category": "예체능계열"
    }
  ],
  "비평": [
    {
      "id": "music-theory",
      "name": "음악학과",
      "category": "예체능계열"
    }
  ],
  "작곡": [
    {
      "id": "composition",
      "name": "작곡과",
      "category": "예체능계열"
    }
  ],
  "편곡": [
    {
      "id": "composition",
      "name": "작곡과",
      "category": "예체능계열"
    }
  ],
  "이론": [
    {
      "id": "composition",
      "name": "작곡과",
      "category": "예체능계열"
    }
  ],
  "성악": [
    {
      "id": "vocal",
      "name": "성악과",
      "category": "예체능계열"
    }
  ],
  "오페라": [
    {
      "id": "vocal",
      "name": "성악과",
      "category": "예체능계열"
    }
  ],
  "발성": [
    {
      "id": "vocal",
      "name": "성악과",
      "category": "예체능계열"
    }
  ],
  "피아노": [
    {
      "id": "piano",
      "name": "피아노학과",
      "category": "예체능계열"
    }
  ],
  "연주": [
    {
      "id": "piano",
      "name": "피아노학과",
      "category": "예체능계열"
    }
  ],
  "레퍼토리": [
    {
      "id": "piano",
      "name": "피아노학과",
      "category": "예체능계열"
    }
  ],
  "관현악": [
    {
      "id": "orchestra",
      "name": "관현악과",
      "category": "예체능계열"
    }
  ],
  "오케스트라": [
    {
      "id": "orchestra",
      "name": "관현악과",
      "category": "예체능계열"
    }
  ],
  "악기": [
    {
      "id": "orchestra",
      "name": "관현악과",
      "category": "예체능계열"
    }
  ],
  "국악": [
    {
      "id": "korean-music",
      "name": "한국음악과",
      "category": "예체능계열"
    }
  ],
  "전통음악": [
    {
      "id": "korean-music",
      "name": "한국음악과",
      "category": "예체능계열"
    }
  ],
  "가야금": [
    {
      "id": "korean-music",
      "name": "한국음악과",
      "category": "예체능계열"
    }
  ],
  "실용음악": [
    {
      "id": "applied-music",
      "name": "실용음악과",
      "category": "예체능계열"
    }
  ],
  "재즈": [
    {
      "id": "applied-music",
      "name": "실용음악과",
      "category": "예체능계열"
    }
  ],
  "프로듀싱": [
    {
      "id": "applied-music",
      "name": "실용음악과",
      "category": "예체능계열"
    }
  ],
  "무용": [
    {
      "id": "dance",
      "name": "무용학과",
      "category": "예체능계열"
    }
  ],
  "안무": [
    {
      "id": "dance",
      "name": "무용학과",
      "category": "예체능계열"
    }
  ],
  "발레": [
    {
      "id": "dance",
      "name": "무용학과",
      "category": "예체능계열"
    }
  ],
  "연극": [
    {
      "id": "theater-film",
      "name": "연극영화학과",
      "category": "예체능계열"
    }
  ],
  "연기": [
    {
      "id": "theater-film",
      "name": "연극영화학과",
      "category": "예체능계열"
    }
  ],
  "생활체육": [
    {
      "id": "social-sports",
      "name": "사회체육학과",
      "category": "예체능계열"
    }
  ],
  "레저": [
    {
      "id": "social-sports",
      "name": "사회체육학과",
      "category": "예체능계열"
    }
  ],
  "건강": [
    {
      "id": "social-sports",
      "name": "사회체육학과",
      "category": "예체능계열"
    }
  ],
  "태권도": [
    {
      "id": "taekwondo",
      "name": "태권도학과",
      "category": "예체능계열"
    }
  ],
  "무도": [
    {
      "id": "taekwondo",
      "name": "태권도학과",
      "category": "예체능계열"
    }
  ],
  "국제보급": [
    {
      "id": "taekwondo",
      "name": "태권도학과",
      "category": "예체능계열"
    }
  ]
};